import trubaPPRPN20PRT from "@/assets/productImgs/rtp/trubaPPRPN20.png";
import trubaRtp from "@/assets/productImgs/rtp/trubaPPR.webp";
import toplipolRTP from "@/assets/productImgs/rtp/toplipolRTP.webp";
import skobaRTP from "@/assets/productImgs/rtp/skobaRTP.webp";
import ugolRTP90 from "@/assets/productImgs/rtp/ugolRTP90.webp";
import trubaVkRTP from "@/assets/productImgs/rtp/trubaVkRTP.webp";
import trubaNrRTP from "@/assets/productImgs/rtp/trubaNrRTP.webp";
import krestavinaRTP from "@/assets/productImgs/rtp/krestavinaRTP.jpg";
import ugolNrRTP from "@/assets/productImgs/rtp/ugolNrRTP.webp";

// RTP praduct data
export const dataRTP = [
  {
    id: 1,
    img: trubaRtp,
    name: "Труба PPR 20х3,4 (PN 20) 4м белый RTP",
    brand: "RTP",
    quantity: "100/4м",
    price: 42,
    allResidual: 4800,
    residualValue: "",
    unit: "м",
    isActive: true,
    category: "trubaPPR",
  },
  {
    id: 2,
    img: trubaRtp,
    name: "Труба PPR GF\PPR 20x3,4 (PN 25) 4м белый RTP",
    brand: "RTP",
    quantity: "100/4м",
    price: 51,
    allResidual: 4800,
    residualValue: "",
    unit: "м",
    isActive: true,
    category: "trubaPPR",
  },
  {
    id: 3,
    img: trubaRtp,
    name: "Труба PPR GF\PPR 32x5,4 (PN 25) 4м белый RTP",
    brand: "RTP",
    quantity: "60/4м",
    price: 127,
    allResidual: 4800,
    residualValue: "",
    unit: "м",
    isActive: true,
    category: "trubaPPR",
  },
  {
    id: 4,
    img: ugolNrRTP,
    name: `Угольник с креплением PPR Н/Р 20х1/2 PN25 белый RTP`,
    brand: "RTP",
    quantity: "75/25 шт",
    price: 70,
    allResidual: 3000,
    residualValue: "",
    unit: "шт",
    isActive: true,
    category: "trubaPPR",
  },
  {
    id: 5,
    img: ugolRTP90,
    name: "Угольник PPR 90° 20ф PN25 белый RTP",
    brand: "RTP",
    quantity: "400/50 шт",
    price: 6,
    allResidual: 40000,
    residualValue: "",
    unit: "шт",
    isActive: true,
    category: "trubaPPR",
  },
  {
    id: 6,
    img: ugolRTP90,
    name: "Угольник PPR 90° 25ф PN25 белый RTP",
    brand: "RTP",
    quantity: "240/40 шт",
    price: 9,
    allResidual: 24000,
    residualValue: "",
    unit: "шт",
    isActive: true,
    category: "trubaPPR",
  },
  {
    id: 7,
    img: ugolRTP90,
    name: "Угольник PPR 90° 32ф PN25 белый RTP",
    brand: "RTP",
    quantity: "140/20 шт",
    price: 18,
    allResidual: 14000,
    residualValue: "",
    unit: "шт",
    isActive: true,
    category: "trubaPPR",
  },
  {
    id: 8,
    img: skobaRTP,
    name: "Длинные скобы для теплого пола (16-20)RTP",
    brand: "RTP",
    quantity: "1000 шт",
    price: 2.5,
    allResidual: 50000,
    residualValue: "",
    unit: "шт",
    isActive: true,
    category: "trubaPPR",
},
{
  id: 9,
  img: toplipolRTP,
  name: "Труба PERT 16х2.0х600 красный RTP",
  brand: "RTP",
  quantity: "600м",
  price: 25,
  allResidual: 30000,
  residualValue: "",
  unit: "м",
  isActive: true,
  category: "trubaPPR",
},
{
    id: 10,
    img: trubaVkRTP,
    name: "Труба ВК ПП 110х2.7х3000 серый RTP",
    brand: "RTP",
    quantity: "10 шт",
    price: 690,
    allResidual: 700,
    residualValue: "",
    unit: "шт",
    isActive: true,
    category: "trubaPPR",
},
{
    id: 11,
    img: trubaVkRTP,
    name: "Труба ВК ПП 110х2.7х1000 серый RTP",
    brand: "RTP",
    quantity: "10 шт",
    price: 260,
    allResidual: 700,
    residualValue: "",
    unit: "шт",
    isActive: true,
    category: "trubaPPR",
},
{
    id: 12,
    img: trubaVkRTP,
    name: "Труба ВК ПП 110х2.7х500 серый RTP",
    brand: "RTP",
    quantity: "10 шт",
    price: 160,
    allResidual: 500,
    residualValue: "",
    unit: "шт",
    isActive: true,
    category: "trubaPPR",
},
{
    id: 13,
    img: trubaVkRTP,
    name: "Труба ВК ПП 50х1,8х1000 серый RTP",
    brand: "RTP",
    quantity: "10 шт",
    price: 95,
    allResidual: 2000,
    residualValue: "",
    unit: "шт",
    isActive: true,
    category: "trubaPPR",
},
{
    id: 14,
    img: trubaNrRTP,
    name: "Труба НК ПП 110х3.4х3000 рыжый RTP",
    brand: "RTP",
    quantity: "10 шт",
    price: 860,
    allResidual: 200,
    residualValue: "",
    unit: "шт",
    isActive: true,
    category: "trubaPPR",
},
{
    id: 15,
    img: trubaNrRTP,
    name: "Труба НК ПП 110х3.4х2000 рыжый RTP",
    brand: "RTP",
    quantity: "10 шт",
    price: 570,
    allResidual: 150,
    residualValue: "",
    unit: "шт",
    isActive: true,
    category: "trubaPPR",
},
{
    id: 16,
    img: trubaNrRTP,
    name: "Труба НК ПП 110х3.4х1000 рыжый RTP",
    brand: "RTP",
    quantity: "10 шт",
    price: 300,
    allResidual: 50,
    residualValue: "",
    unit: "шт",
    isActive: true,
    category: "trubaPPR",
},
{
    id: 17,
    img: krestavinaRTP,
    name: "Крестовина одноплоскостная ВК ПП 110/110/100 87° К,серый RTP",
    brand: "RTP",
    quantity: "18 шт",
    price: 220,
    allResidual: 0,
    residualValue: "",
    unit: "шт",
    isActive: false,
    category: "trubaPPR",
},
];

// RTP praduct list export
export const allDataRTP = dataRTP.map((item) => ({
  ...item,
  residualValue: item.price * item.allResidual,
}));


// products count
export const productsCount = allDataRTP.length;

// all products  residual valyue
export const totalResidualValue = allDataRTP.reduce(
  (sum, item) => sum + item.residualValue,
  0
);
