import trubaPPRPN20PRT from "@/assets/productImgs/rtp/trubaPPRPN20.png";
import trubaRtp from "@/assets/productImgs/rtp/trubaPPR.webp";
import toplipolRTP from "@/assets/productImgs/rtp/toplipolRTP.webp";
import skobaRTP from "@/assets/productImgs/rtp/skobaRTP.webp";
import ugolRTP90 from "@/assets/productImgs/rtp/ugolRTP90.webp";
import trubaVkRTP from "@/assets/productImgs/rtp/trubaVkRTP.webp";
import trubaNrRTP from "@/assets/productImgs/rtp/trubaNrRTP.webp";
import krestavinaRTP from "@/assets/productImgs/rtp/krestavinaRTP.jpg";
import ugolNrRTP from "@/assets/productImgs/rtp/ugolNrRTP.webp";

// RTP praduct data
const dataRTP = [
  {
    id: 1,
    img: trubaRtp,
    name: "Труба PPR/GF/PPR  20х3,4 PN20 белый 4м РТП",
    brand: "RTP",
    quantity: "60/4м",
    price: 81,
    allResidual: 4800,
    residualValue: "",
    unit: "м",
    isActive: true,
    category: "trubaPPR",
  },
  {
    id: 2,
    img: trubaRtp,
    name: "Труба PPR/GF/PPR  20х3,4 PN25 белый 4м РТП",
    brand: "RTP",
    quantity: "60/4м",
    price: 81,
    allResidual: 4800,
    residualValue: "",
    unit: "м",
    isActive: true,
    category: "trubaPPR",
  },
  {
    id: 3,
    img: trubaRtp,
    name: "Труба PPR/GF/PPR  32х5,4 PN25 белый 4м РТП",
    brand: "RTP",
    quantity: "60/4м",
    price: 81,
    allResidual: 4800,
    residualValue: "",
    unit: "м",
    isActive: true,
    category: "trubaPPR",
  },
  {
    id: 5,
    img: ugolNrRTP,
    name: "Угольник комбинированный с креплением PPR наружная резьба 20х 1/2,  белый, РТП",
    brand: "RTP",
    quantity: "75/25 шт",
    price: 62,
    allResidual: 3000,
    residualValue: "",
    unit: "шт",
    isActive: true,
    category: "trubaPPR",
  },
  {
    id: 7,
    img: ugolRTP90,
    name: "Угольник PPR  20х90, PN25 белый, РТП",
    brand: "RTP",
    quantity: "400/50 шт",
    price: 5,
    allResidual: 40000,
    residualValue: "",
    unit: "шт",
    isActive: true,
    category: "trubaPPR",
  },
  {
    id: 7,
    img: ugolRTP90,
    name: "Угольник PPR  25х90, PN25 белый, РТП",
    brand: "RTP",
    quantity: "240/40 шт",
    price: 8,
    allResidual: 24000,
    residualValue: "",
    unit: "шт",
    isActive: true,
    category: "trubaPPR",
  },
  {
    id: 7,
    img: ugolRTP90,
    name: "Угольник PPR  32х90, PN25 белый, РТП",
    brand: "RTP",
    quantity: "140/20 шт",
    price: 17,
    allResidual: 14000,
    residualValue: "",
    unit: "шт",
    isActive: true,
    category: "trubaPPR",
  },
  {
    id: 6,
    img: skobaRTP,
    name: "Длинные скобы для теплого пола (16-20)RTP",
    brand: "RTP",
    quantity: "1000 шт",
    price: 2.5,
    allResidual: 50000,
    residualValue: "",
    unit: "шт",
    isActive: true,
    category: "trubaPPR",
},
{
  id: 4,
  img: toplipolRTP,
  name: "Труба PERT 16х2,0х600, красный, РТП",
  brand: "RTP",
  quantity: "600м",
  price: 25,
  allResidual: 30000,
  residualValue: "",
  unit: "м",
  isActive: true,
  category: "trubaPPR",
},
{
    id: 41,
    img: trubaVkRTP,
    name: "Труба ВК ПП 110х2,7х3000, серый, РТП",
    brand: "RTP",
    quantity: "10 шт",
    price: 690,
    allResidual: 700,
    residualValue: "",
    unit: "шт",
    isActive: true,
    category: "trubaPPR",
},
{
    id: 42,
    img: trubaVkRTP,
    name: "Труба ВК ПП 110х2,7х1000, серый, РТП",
    brand: "RTP",
    quantity: "10 шт",
    price: 260,
    allResidual: 700,
    residualValue: "",
    unit: "шт",
    isActive: true,
    category: "trubaPPR",
},
{
    id: 43,
    img: trubaVkRTP,
    name: "Труба ВК ПП 110х2,7х500, серый, РТП",
    brand: "RTP",
    quantity: "10 шт",
    price: 160,
    allResidual: 500,
    residualValue: "",
    unit: "шт",
    isActive: true,
    category: "trubaPPR",
},
{
    id: 44,
    img: trubaVkRTP,
    name: "Труба ВК ПП 50х1,8х1000, серый, РТП",
    brand: "RTP",
    quantity: "10 шт",
    price: 95,
    allResidual: 2000,
    residualValue: "",
    unit: "шт",
    isActive: true,
    category: "trubaPPR",
},
{
    id: 45,
    img: trubaNrRTP,
    name: "Труба НК ПП 110х3,4х3000, рыжий,РТП",
    brand: "RTP",
    quantity: "10 шт",
    price: 860,
    allResidual: 200,
    residualValue: "",
    unit: "шт",
    isActive: true,
    category: "trubaPPR",
},
{
    id: 46,
    img: trubaNrRTP,
    name: "Труба НК ПП 110х3,4х2000, рыжий,РТП",
    brand: "RTP",
    quantity: "10 шт",
    price: 570,
    allResidual: 150,
    residualValue: "",
    unit: "шт",
    isActive: true,
    category: "trubaPPR",
},
{
    id: 45,
    img: trubaNrRTP,
    name: "Труба НК ПП 110х3,4х1000, рыжий,РТП",
    brand: "RTP",
    quantity: "10 шт",
    price: 300,
    allResidual: 50,
    residualValue: "",
    unit: "шт",
    isActive: true,
    category: "trubaPPR",
},
{
    id: 48,
    img: krestavinaRTP,
    name: "Крестовина одноплоскостная ВК ПП 110/110/110х87, серый,РТП",
    brand: "RTP",
    quantity: "20 шт",
    price: 300,
    allResidual: 40,
    residualValue: "",
    unit: "шт",
    isActive: true,
    category: "trubaPPR",
},
];

// RTP praduct list export
export const allDataRTP = dataRTP.map((item) => ({
  ...item,
  residualValue: item.price * item.allResidual,
}));


// products count
export const productsCount = allDataRTP.length;

// all products  residual valyue
export const totalResidualValue = allDataRTP.reduce(
  (sum, item) => sum + item.residualValue,
  0
);
