
import mentalaplast from "@/assets/productImgs/rtp/metalaplastRTP.webp"


///   test boshlanishi 
import trubaRtp from "@/assets/productImgs/rtp/trubaPPRPN25.webp";
import trubaPPRPN20 from "@/assets/productImgs/rtp/trubaPPRPN20.webp";

// mufta ppr rtp
import muftaPPR from "@/assets/productImgs/rtp/muftaPPR.webp";
import muftaPPRVrNr from "@/assets/productImgs/rtp/muftaPPRVrNr.webp";
import muftaPPRVrVr from "@/assets/productImgs/rtp/muftaPPRVrVr.webp";

// ugolnik ppr rtp
import ugolRTP90 from "@/assets/productImgs/rtp/ugolRTP90.webp";
import ugolRTP45 from "@/assets/productImgs/rtp/ugolRTP45.webp";

// traynik ppr rtp
import traynikPPR from "@/assets/productImgs/rtp/traynikPPR.webp";
import traynikPPRPr from "@/assets/productImgs/rtp/traynikPPRPr.webp";
import traynikPPRVr from "@/assets/productImgs/rtp/traynikPPRVr.webp";
import traynikPPRNr from "@/assets/productImgs/rtp/traynikPPRNr.webp";

// kran , vintel ppr rtp
import kranPPR from "@/assets/productImgs/rtp/kranPPR.webp";
import vintelPPR from "@/assets/productImgs/rtp/vintelPPR.webp";
import kranPPRRdPr from "@/assets/productImgs/rtp/kranPPRRdPr.webp";
import kranPPRRdUg from "@/assets/productImgs/rtp/kranPPRRdUg.webp";

// mufta komprivni rezba  ppr rtp 
import muftaPPRKbNr from "@/assets/productImgs/rtp/muftaPPRKbNr.webp";
import muftaPPRKbVr from "@/assets/productImgs/rtp/muftaPPRKbVr.webp";
import muftaPPRAmrVr from "@/assets/productImgs/rtp/muftaPPRAmrVr.webp";
import muftaPPRAmrNr from "@/assets/productImgs/rtp/muftaPPRAmrNr.webp";

// ugolnik krep ppr rtp
import ugolNrRTP from "@/assets/productImgs/rtp/ugolNrRTP.webp";
import ugolVrRTP from "@/assets/productImgs/rtp/ugolVrRTP.webp";
import shablonNr from "@/assets/productImgs/rtp/shablonNr.webp";
import shablonVr from "@/assets/productImgs/rtp/shablonVr.webp";

// drugoy fiting ppr rtp
import oporaPPR from "@/assets/productImgs/rtp/oporaPPR.webp";
import mostikPPR from "@/assets/productImgs/rtp/mostikPPR.webp";
import obratniKlapn from "@/assets/productImgs/rtp/obratniKlapn.webp";
import zagulushkaPPR from "@/assets/productImgs/rtp/zagulushkaPPR.webp";

//Труба PERT (тёплый пол) + Скобы
import toplipolRTP from "@/assets/productImgs/rtp/toplipolRTP.webp";
import toplipolRTPSer from "@/assets/productImgs/rtp/toplipolRTPSer.webp";
import skobaRTP from "@/assets/productImgs/rtp/skobaRTP.webp";

//rubaVK — Трубы ВК (внутренняя канализация, серый)
import trubaVkRTP from "@/assets/productImgs/rtp/trubaVkRTP.webp";
import trubaVkRTP50 from "@/assets/productImgs/rtp/trubaVkRTP50.webp";

//fitingVK — Фитинги ВК (отводы, тройники, муфты, хомуты и др.)
import patrubkaVk from "@/assets/productImgs/rtp/patrubkaVk.webp";
import patrubkaVkGip50 from "@/assets/productImgs/rtp/patrubkaVkGip50.webp";
import patrubkaVk110 from "@/assets/productImgs/rtp/patrubkaVk110.webp";
// otvod vk
import otvod5045 from "@/assets/productImgs/rtp/otvod5045.webp";
import otvod5087 from "@/assets/productImgs/rtp/otvod5087.webp";
import otvod7545 from "@/assets/productImgs/rtp/otvod7545.webp";
import otvod7587 from "@/assets/productImgs/rtp/otvod7587.webp";
import otvod11015 from "@/assets/productImgs/rtp/otvod11015.webp";
import otvod11030 from "@/assets/productImgs/rtp/otvod11030.webp";
import otvod11045 from "@/assets/productImgs/rtp/otvod11045.webp";
import otvod11067 from "@/assets/productImgs/rtp/otvod11067.webp";
import otvod11087 from "@/assets/productImgs/rtp/otvod11087.webp";
// traynik vk
import traynikVk505045 from "@/assets/productImgs/rtp/traynikVk505045.webp"
import traynikVk505087 from "@/assets/productImgs/rtp/traynikVk505087.webp"
import traynik757587 from "@/assets/productImgs/rtp/traynik757587.webp"
import traynik757545 from "@/assets/productImgs/rtp/traynik757545.webp"
import traynik11011045 from "@/assets/productImgs/rtp/traynik11011045.webp"
import traynik11011087 from "@/assets/productImgs/rtp/traynik11011087.webp"
import traynik1107545 from "@/assets/productImgs/rtp/traynik1107545.webp"
import traynik1105087 from "@/assets/productImgs/rtp/traynik1105087.webp"
import traynik1105045 from "@/assets/productImgs/rtp/traynik1105045.webp"

// import revizyaNk from "@/assets/productImgs/rtp/reviziyaNk.webp"
// import revizyaNk160110 from "@/assets/productImgs/rtp/reviziyaNk160110.webp"
import reviziyaVk from "@/assets/productImgs/rtp/reviziyaVk.jpg"
import reduksiya7550 from "@/assets/productImgs/rtp/reduksiya7550.webp"
import reduksiya11050 from "@/assets/productImgs/rtp/reduksiya11050.webp"
import perehodChu from "@/assets/productImgs/rtp/perehodChu.webp"
import zagulushkaVk from "@/assets/productImgs/rtp/zagulushkaVk.webp"
import muftaVk from "@/assets/productImgs/rtp/muftaVk.webp"
import muftaVk75 from "@/assets/productImgs/rtp/muftaVk75.webp"
import zont110 from "@/assets/productImgs/rtp/zont110.webp"
import zont50 from "@/assets/productImgs/rtp/zont50.webp"
import chetvertak11050lev from "@/assets/productImgs/rtp/chetvertak11050lev.jpg"
import chetvertak11050prv from "@/assets/productImgs/rtp/chetvertak11050prv.jpg"
import chetvertak110110 from "@/assets/productImgs/rtp/chetvertak110110.webp"
import kres from "@/assets/productImgs/rtp/kres.jpg"
import kres11050 from "@/assets/productImgs/rtp/kres11050.jpg"
import kres1105045 from "@/assets/productImgs/rtp/kres1105045.webp"
import obratniyKlapn50 from "@/assets/productImgs/rtp/obratniyKlapn50.webp"
import obratniyKlapn110 from "@/assets/productImgs/rtp/obratniyKlapn110.webp"
import klipsVk from "@/assets/productImgs/rtp/klipsVk.jpg"
import xomut from "@/assets/productImgs/rtp/xomut.jpg"

// otvod nk
import trubaNrRTP from "@/assets/productImgs/rtp/trubaNrRTP.webp";
import otvodNk from "@/assets/productImgs/rtp/otvodNk.jpg"
import otvodNk45 from "@/assets/productImgs/rtp/otvodNr45.jpg"
import obratniyKlapn160 from "@/assets/productImgs/rtp/obratniyKlapn160.webp"
import obratniyKlapnNk110 from "@/assets/productImgs/rtp/obratniyKlapnNk110.webp"
import muftaNk from "@/assets/productImgs/rtp/muftaNk.webp"
import reduksiyaNk160110 from "@/assets/productImgs/rtp/reduksiyaNk160110.webp"
import reviziyaNk160110 from "@/assets/productImgs/rtp/reviziyaNk160110.webp"
import reviziyaNk from "@/assets/productImgs/rtp/reviziyaNk.webp"
import zagulushkaNk from "@/assets/productImgs/rtp/zagulushkaNk.webp"
import traynikNk11045 from "@/assets/productImgs/rtp/traynikNk11045.webp"
import traynikNk11087 from "@/assets/productImgs/rtp/traynikNk11087.webp"
import traynikNk16011087 from "@/assets/productImgs/rtp/traynik16011087.webp"


// RTP praduct data
export const dataRTPAdir = [

  // ═══════════════════════════════════════════════════════════
  // 1. trubaPPR — Трубы PPR (PN20 и PN25 GF)
  // ═══════════════════════════════════════════════════════════
  {
    id: 1,
    img: trubaPPRPN20,
    name: "Труба PPR 20х3,4 (PN 20) 4м белый RTP",
    brand: "RTP",
    quantity: "100/4м",
    price: 53,
    unit: "м",
    category: "trubaPPR",
    categoryName: "Труба ППР",
    allResidual: 22700,
    residualValue: "",
    isActive: true,
  },
  {
    id: 2,
    img: trubaPPRPN20,
    name: "Труба PPR 25x4,2 (PN 20) 4м белый RTP",
    brand: "RTP",
    quantity: "100/4м",
    price: 88,
    unit: "м",
    category: "trubaPPR",
    categoryName: "Труба ППР",
    allResidual: 900,
    residualValue: "",
    isActive: true,
  },
  {
    id: 3,
    img: trubaPPRPN20,
    name: "Труба PPR 32x5,4 (PN 20) 4м белый RTP",
    brand: "RTP",
    quantity: "60/4м",
    price: 148,
    unit: "м",
    category: "trubaPPR",
    categoryName: "Труба ППР",
    allResidual: 0,
    residualValue: "",
    isActive: false,
  },
  {
    id: 4,
    img: trubaPPRPN20,
    name: "Труба PPR 40х6,7 (PN 20) 4м белый RTP",
    brand: "RTP",
    quantity: "40/4м",
    price: 192,
    unit: "м",
    category: "trubaPPR",
    categoryName: "Труба ППР",
    allResidual: 0,
    residualValue: "",
    isActive: false,
  },
  {
    id: 5,
    img: trubaPPRPN20,
    name: "Труба PPR 50x8,3 (PN 20) 4м белый RTP",
    brand: "RTP",
    quantity: "32/4м",
    price: 308,
    unit: "м",
    category: "trubaPPR",
    categoryName: "Труба ППР",
    allResidual: 0,
    residualValue: "",
    isActive: false,
  },
  {
    id: 6,
    img: trubaRtp,
    name: "Труба PPR GF\\PPR 20x3,4 (PN 25) 4м белый RTP",
    brand: "RTP",
    quantity: "100/4м",
    price: 64,
    unit: "м",
    category: "trubaPPR",
    categoryName: "Труба ППР",
    allResidual: 14000,
    residualValue: "",
    isActive: true,
  },
  {
    id: 7,
    img: trubaRtp,
    name: "Труба PPR GF\\PPR 25x4,2 (PN 25) 4м белый RTP",
    brand: "RTP",
    quantity: "100/4м",
    price: 93,
    unit: "м",
    category: "trubaPPR",
    categoryName: "Труба ППР",
    allResidual: 2900,
    residualValue: "",
    isActive: true,
  },
  {
    id: 8,
    img: trubaRtp,
    name: "Труба PPR GF\\PPR 32x5,4 (PN 25) 4м белый RTP",
    brand: "RTP",
    quantity: "60/4м",
    price: 158,
    unit: "м",
    category: "trubaPPR",
    categoryName: "Труба ППР",
    allResidual: 11160,
    residualValue: "",
    isActive: true,
  },
  {
    id: 9,
    img: trubaRtp,
    name: "Труба PPR GF\\PPR 40x6,7 (PN 25) 4м белый RTP",
    brand: "RTP",
    quantity: "40/4м",
    price: 300,
    unit: "м",
    category: "trubaPPR",
    categoryName: "Труба ППР",
    allResidual: 0,
    residualValue: "",
    isActive: false,
  },
  {
    id: 10,
    img: trubaRtp,
    name: "Труба PPR GF\\PPR 50x8,3 (PN 25) 4м белый RTP",
    brand: "RTP",
    quantity: "32/4м",
    price: 352,
    unit: "м",
    category: "trubaPPR",
    categoryName: "Труба ППР",
    allResidual: 0,
    residualValue: "",
    isActive: false,
  },

  // ═══════════════════════════════════════════════════════════
  // 2. muftaPPR — Муфта соединительная + Муфта переходная
  // ═══════════════════════════════════════════════════════════
  {
    id: 11,
    img: muftaPPR,
    name: "Муфта соединительная PPR 20ф PN25 белый RTP",
    brand: "RTP",
    quantity: "500/50 шт",
    price: 6,
    unit: "шт",
    category: "muftaPPR",
    categoryName: "Муфта ППР",
    allResidual: 37500,
    residualValue: "",
    isActive: true,
  },
  {
    id: 12,
    img: muftaPPR,
    name: "Муфта соединительная PPR 25ф PN25 белый RTP",
    brand: "RTP",
    quantity: "400/50 шт",
    price: 8,
    unit: "шт",
    category: "muftaPPR",
    categoryName: "Муфта ППР",
    allResidual: 25000,
    residualValue: "",
    isActive: true,
  },
  {
    id: 13,
    img: muftaPPR,
    name: "Муфта соединительная PPR 32ф PN25 белый RTP",
    brand: "RTP",
    quantity: "245/35 шт",
    price: 16,
    unit: "шт",
    category: "muftaPPR",
    categoryName: "Муфта ППР",
    allResidual: 14700,
    residualValue: "",
    isActive: true,
  },
  {
    id: 14,
    img: muftaPPR,
    name: "Муфта соединительная PPR 40ф PN25 белый RTP",
    brand: "RTP",
    quantity: "140/20 шт",
    price: 28,
    unit: "шт",
    category: "muftaPPR",
    categoryName: "Муфта ППР",
    allResidual: 1400,
    residualValue: "",
    isActive: true,
  },
  {
    id: 15,
    img: muftaPPR,
    name: "Муфта соединительная PPR 50ф PN25 белый RTP",
    brand: "RTP",
    quantity: "100/10 шт",
    price: 55,
    unit: "шт",
    category: "muftaPPR",
    categoryName: "Муфта ППР",
    allResidual: 200,
    residualValue: "",
    isActive: true,
  },
  {
    id: 16,
    img: muftaPPR,
    name: "Муфта соединительная PPR 63ф PN25 белый RTP",
    brand: "RTP",
    quantity: "24/6 шт",
    price: 90,
    unit: "шт",
    category: "muftaPPR",
    categoryName: "Муфта ППР",
    allResidual: 168,
    residualValue: "",
    isActive: true,
  },


  // Муфта переходная PPR ВР\\НР 
  {
    id: 17,
    img: muftaPPRVrNr,
    name: "Муфта переходная PPR ВР\\НР 25\\20 PN25 белый RTP",
    brand: "RTP",
    quantity: "350/50 шт",
    price: 5,
    unit: "шт",
    category: "muftaPPR",
    categoryName: "Муфта ППР",
    allResidual: 0,
    residualValue: "",
    isActive: false,
  },
  {
    id: 18,
    img: muftaPPRVrNr,
    name: "Муфта переходная PPR ВР\\НР 32\\20 PN25 белый RTP",
    brand: "RTP",
    quantity: "270/40 шт",
    price: 7,
    unit: "шт",
    category: "muftaPPR",
    categoryName: "Муфта ППР",
    allResidual: 0,
    residualValue: "",
    isActive: false,
  },
  {
    id: 19,
    img: muftaPPRVrNr,
    name: "Муфта переходная PPR ВР\\НР 32\\25 PN25 белый RTP",
    brand: "RTP",
    quantity: "200/50 шт",
    price: 7,
    unit: "шт",
    category: "muftaPPR",
    categoryName: "Муфта ППР",
    allResidual: 0,
    residualValue: "",
    isActive: false,
  },
  {
    id: 20,
    img: muftaPPRVrNr,
    name: "Муфта переходная PPR ВР\\НР 40\\20 PN25 белый RTP",
    brand: "RTP",
    quantity: "160/20 шт",
    price: 12,
    unit: "шт",
    category: "muftaPPR",
    categoryName: "Муфта ППР",
    allResidual: 0,
    residualValue: "",
    isActive: false,
  },
  {
    id: 21,
    img: muftaPPRVrNr,
    name: "Муфта переходная PPR ВР\\НР 40\\25 PN25 белый RTP",
    brand: "RTP",
    quantity: "160/20 шт",
    price: 15,
    unit: "шт",
    category: "muftaPPR",
    categoryName: "Муфта ППР",
    allResidual: 0,
    residualValue: "",
    isActive: false,
  },
  {
    id: 22,
    img: muftaPPRVrNr,
    name: "Муфта переходная PPR ВР\\НР 40\\32 PN25 белый RTP",
    brand: "RTP",
    quantity: "120/20 шт",
    price: 15,
    unit: "шт",
    category: "muftaPPR",
    categoryName: "Муфта ППР",
    allResidual: 0,
    residualValue: "",
    isActive: false,
  },

  //  Муфта переходная PPR ВР\\ВР

  {
    id: 23,
    img: muftaPPRVrVr,
    name: "Муфта переходная PPR ВР\\ВР 25\\20 PN25 белый RTP",
    brand: "RTP",
    quantity: "200/50 шт",
    price: 8,
    unit: "шт",
    category: "muftaPPR",
    categoryName: "Муфта ППР",
    allResidual: 0,
    residualValue: "",
    isActive: false,
  },
  {
    id: 24,
    img: muftaPPRVrVr,
    name: "Муфта переходная PPR ВР\\ВР 32\\20 PN25 белый RTP",
    brand: "RTP",
    quantity: "250/25 шт",
    price: 15,
    unit: "шт",
    category: "muftaPPR",
    categoryName: "Муфта ППР",
    allResidual: 0,
    residualValue: "",
    isActive: false,
  },
  {
    id: 25,
    img: muftaPPRVrVr,
    name: "Муфта переходная PPR ВР\\ВР 32\\25 PN25 белый RTP",
    brand: "RTP",
    quantity: "150/25 шт",
    price: 17,
    unit: "шт",
    category: "muftaPPR",
    categoryName: "Муфта ППР",
    allResidual: 0,
    residualValue: "",
    isActive: false,
  },
  {
    id: 26,
    img: muftaPPRVrVr,
    name: "Муфта переходная PPR ВР\\ВР 40\\32 PN25 белый RTP",
    brand: "RTP",
    quantity: "200/20 шт",
    price: 20,
    unit: "шт",
    category: "muftaPPR",
    categoryName: "Муфта ППР",
    allResidual: 0,
    residualValue: "",
    isActive: false,
  },

  // ═══════════════════════════════════════════════════════════
  // 3. ugolnikPPR — Угольник 45° + 90°
  // ═══════════════════════════════════════════════════════════
  {
    id: 27,
    img: ugolRTP45,
    name: "Угольник PPR 45° 20ф PN25 белый RTP",
    brand: "RTP",
    quantity: "525/75 шт",
    price: 6,
    unit: "шт",
    category: "ugolnikPPR",
    categoryName: "Уголник ППР",
    allResidual: 0,
    residualValue: "",
    isActive: false,
  },
  {
    id: 28,
    img: ugolRTP45,
    name: "Угольник PPR 45° 25ф PN25 белый RTP",
    brand: "RTP",
    quantity: "320/40 шт",
    price: 9,
    unit: "шт",
    category: "ugolnikPPR",
    categoryName: "Уголник ППР",
    allResidual: 0,
    residualValue: "",
    isActive: false,
  },
  {
    id: 29,
    img: ugolRTP45,
    name: "Угольник PPR 45° 32ф PN25 белый RTP",
    brand: "RTP",
    quantity: "150/25 шт",
    price: 19,
    unit: "шт",
    category: "ugolnikPPR",
    categoryName: "Уголник ППР",
    allResidual: 0,
    residualValue: "",
    isActive: false,
  },
  {
    id: 30,
    img: ugolRTP45,
    name: "Угольник PPR 45° 40ф PN25 белый RTP",
    brand: "RTP",
    quantity: "108/12 шт",
    price: 40,
    unit: "шт",
    category: "ugolnikPPR",
    allResidual: 0,
    residualValue: "",
    isActive: false,
  },
  {
    id: 31,
    img: ugolRTP45,
    name: "Угольник PPR 45° 50ф PN25 белый RTP",
    brand: "RTP",
    quantity: "56/7 шт",
    price: 55,
    unit: "шт",
    category: "ugolnikPPR",
    categoryName: "Уголник ППР",
    allResidual: 0,
    residualValue: "",
    isActive: false,
  },

  {
    id: 32,
    img: ugolRTP45,
    name: "Угольник PPR 45° 63ф PN25 белый RTP",
    brand: "RTP",
    quantity: "30/5 шт",
    price: 90,
    unit: "шт",
    category: "ugolnikPPR",
    categoryName: "Уголник ППР",
    allResidual: 0,
    residualValue: "",
    isActive: false,
  },
  {
    id: 33,
    img: ugolRTP90,
    name: "Угольник PPR 90° 20ф PN25 белый RTP",
    brand: "RTP",
    quantity: "400/50 шт",
    price: 7,
    unit: "шт",
    category: "ugolnikPPR",
    categoryName: "Уголник ППР",
    allResidual: 70400,
    residualValue: "",
    isActive: true,
  },
  {
    id: 34,
    img: ugolRTP90,
    name: "Угольник PPR 90° 25ф PN25 белый RTP",
    brand: "RTP",
    quantity: "240/40 шт",
    price: 10,
    unit: "шт",
    category: "ugolnikPPR",
    categoryName: "Уголник ППР",
    allResidual: 31200,
    residualValue: "",
    isActive: true,
  },
  {
    id: 35,
    img: ugolRTP90,
    name: "Угольник PPR 90° 32ф PN25 белый RTP",
    brand: "RTP",
    quantity: "140/20 шт",
    price: 20,
    unit: "шт",
    category: "ugolnikPPR",
    categoryName: "Уголник ППР",
    allResidual: 21980,
    residualValue: "",
    isActive: true,
  },
  {
    id: 36,
    img: ugolRTP90,
    name: "Угольник PPR 90° 40ф PN25 белый RTP",
    brand: "RTP",
    quantity: "80/10 шт",
    price: 40,
    unit: "шт",
    category: "ugolnikPPR",
    categoryName: "Уголник ППР",
    allResidual: 0,
    residualValue: "",
    isActive: false,
  },
  {
    id: 37,
    img: ugolRTP90,
    name: "Угольник PPR 90° 50ф PN25 белый RTP",
    brand: "RTP",
    quantity: "48/6 шт",
    price: 80,
    unit: "шт",
    category: "ugolnikPPR",
    categoryName: "Уголник ППР",
    allResidual: 0,
    residualValue: "",
    isActive: false,
  },
  {
    id: 38,
    img: ugolRTP90,
    name: "Угольник PPR 90° 63ф PN25 белый RTP",
    brand: "RTP",
    quantity: "24/4 шт",
    price: 100,
    unit: "шт",
    category: "ugolnikPPR",
    categoryName: "Уголник ППР",
    allResidual: 0,
    residualValue: "",
    isActive: false,
  },

  // ═══════════════════════════════════════════════════════════
  // 4. troynikPPR — Тройник + Тройник переходной
  // ═══════════════════════════════════════════════════════════
  {
    id: 39,
    img: traynikPPR,
    name: "Тройник PPR 20ф PN25 белый RTP",
    brand: "RTP",
    quantity: "280/40 шт",
    price: 8,
    unit: "шт",
    category: "troynikPPR",
    categoryName: "Тройник ППР",
    allResidual: 29120,
    residualValue: "",
    isActive: true,
  },
  {
    id: 40,
    img: traynikPPR,
    name: "Тройник PPR 25ф PN25 белый RTP",
    brand: "RTP",
    quantity: "175/25 шт",
    price: 14,
    unit: "шт",
    category: "troynikPPR",
    categoryName: "Тройник ППР",
    allResidual: 11900,
    residualValue: "",
    isActive: true,
  },
  {
    id: 41,
    img: traynikPPR,
    name: "Тройник PPR 32ф PN25 белый RTP",
    brand: "RTP",
    quantity: "105/15 шт",
    price: 22,
    unit: "шт",
    category: "troynikPPR",
    categoryName: "Тройник ППР",
    allResidual: 0,
    residualValue: "",
    isActive: false,
  },
  {
    id: 42,
    img: traynikPPR,
    name: "Тройник PPR 40ф PN25 белый RTP",
    brand: "RTP",
    quantity: "64/8 шт",
    price: 40,
    unit: "шт",
    category: "troynikPPR",
    categoryName: "Тройник ППР",
    allResidual: 0,
    residualValue: "",
    isActive: false,
  },
  {
    id: 43,
    img: traynikPPR,
    name: "Тройник PPR 50ф PN25 белый RTP",
    brand: "RTP",
    quantity: "42/6 шт",
    price: 80,
    unit: "шт",
    category: "troynikPPR",
    categoryName: "Тройник ППР",
    allResidual: 0,
    residualValue: "",
    isActive: false,
  },
  {
    id: 44,
    img: traynikPPR,
    name: "Тройник PPR 63ф PN25 белый RTP",
    brand: "RTP",
    quantity: "24/2 шт",
    price: 120,
    unit: "шт",
    category: "troynikPPR",
    categoryName: "Тройник ППР",
    allResidual: 0,
    residualValue: "",
    isActive: false,
  },
 
  // traynok ppr rtp perehadniy
  {
    id: 45,
    img: traynikPPRPr,
    name: "Тройник переходной PPR 25\\20\\25ф PN25 белый RTP",
    brand: "RTP",
    quantity: "360/60 шт",
    price: 12,
    unit: "шт",
    category: "troynikPPR",
    categoryName: "Тройник ППР",
    allResidual: 0,
    residualValue: "",
    isActive: false,
  },
  {
    id: 46,
    img: traynikPPRPr,
    name: "Тройник переходной PPR 32\\20\\32ф PN25 белый RTP",
    brand: "RTP",
    quantity: "105/15 шт",
    price: 20,
    unit: "шт",
    category: "troynikPPR",
    categoryName: "Тройник ППР",
    allResidual: 0,
    residualValue: "",
    isActive: false,
  },
  {
    id: 47,
    img: traynikPPRPr,
    name: "Тройник переходной PPR 32\\25\\32ф PN25 белый RTP",
    brand: "RTP",
    quantity: "105/15 шт",
    price: 20,
    unit: "шт",
    category: "troynikPPR",
    categoryName: "Тройник ППР",
    allResidual: 0,
    residualValue: "",
    isActive: false,
  },
  {
    id: 48,
    img: traynikPPRPr,
    name: "Тройник переходной PPR 40\\20\\40ф PN25 белый RTP",
    brand: "RTP",
    quantity: "80/10 шт",
    price: 40,
    unit: "шт",
    category: "troynikPPR",
    categoryName: "Тройник ППР",
    allResidual: 0,
    residualValue: "",
    isActive: false,
  },
  {
    id: 49,
    img: traynikPPRPr,
    name: "Тройник переходной PPR 40\\25\\40ф PN25 белый RTP",
    brand: "RTP",
    quantity: "90/9 шт",
    price: 40,
    unit: "шт",
    category: "troynikPPR",
    categoryName: "Тройник ППР",
    allResidual: 0,
    residualValue: "",
    isActive: false,
  },
  {
    id: 50,
    img: traynikPPRPr,
    name: "Тройник переходной PPR 40\\32\\40ф PN25 белый RTP",
    brand: "RTP",
    quantity: "81/9 шт",
    price: 45,
    unit: "шт",
    category: "troynikPPR",
    categoryName: "Тройник ППР",
    allResidual: 0,
    residualValue: "",
    isActive: false,
  },

  // traynik ppr rtp rezba
  {
    id: 51,
    img: traynikPPRVr,
    name: "Тройник комбинированный с В\\Р 20х1\\2 PN25 белый RTP",
    brand: "RTP",
    quantity: "90/15 шт",
    price: 55,
    unit: "шт",
    category: "troynikPPR",
    categoryName: "Тройник ППР",
    allResidual: 0,
    residualValue: "",
    isActive: false,
  },
  {
    id: 52,
    img: traynikPPRVr,
    name: "Тройник комбинированный с В\\Р 25х1\\2 PN25 белый RTP",
    brand: "RTP",
    quantity: "80/20 шт",
    price: 72,
    unit: "шт",
    category: "troynikPPR",
    categoryName: "Тройник ППР",
    allResidual: 0,
    residualValue: "",
    isActive: false,
  },
  {
    id: 53,
    img: traynikPPRVr,
    name: "Тройник комбинированный с В\\Р 32х1\\2 PN25 белый RTP",
    brand: "RTP",
    quantity: "40/10 шт",
    price: 77,
    unit: "шт",
    category: "troynikPPR",
    categoryName: "Тройник ППР",
    allResidual: 0,
    residualValue: "",
    isActive: false,
  },
  {
    id: 54,
    img: traynikPPRVr,
    name: "Тройник комбинированный с В\\Р 25х3\\4 PN25 белый RTP",
    brand: "RTP",
    quantity: "60/55 шт",
    price: 83,
    unit: "шт",
    category: "troynikPPR",
    categoryName: "Тройник ППР",
    allResidual: 0,
    residualValue: "",
    isActive: false,
  },
  {
    id: 55,
    img: traynikPPRNr,
    name: "Тройник комбинированный с Н\\Р 20х1\\2 PN25 белый RTP",
    brand: "RTP",
    quantity: "90/15 шт",
    price: 66,
    unit: "шт",
    category: "troynikPPR",
    categoryName: "Тройник ППР",
    allResidual: 0,
    residualValue: "",
    isActive: false,
  },
  {
    id: 56,
    img: traynikPPRNr,
    name: "Тройник комбинированный с Н\\Р 25х1\\2 PN25 белый RTP",
    brand: "RTP",
    quantity: "80/20 шт",
    price: 77,
    unit: "шт",
    category: "troynikPPR",
    categoryName: "Тройник ППР",
    allResidual: 0,
    residualValue: "",
    isActive: false,
  },
  {
    id: 57,
    img: traynikPPRNr,
    name: "Тройник комбинированный с Н\\Р 25х3\\4 PN25 белый RTP",
    brand: "RTP",
    quantity: "60/15 шт",
    price: 88,
    unit: "шт",
    category: "troynikPPR",
    categoryName: "Тройник ППР",
    allResidual: 0,
    residualValue: "",
    isActive: false,
  },
  {
    id: 58,
    img: traynikPPRNr,
    name: "Тройник комбинированный с Н\\Р 32х1\\2 PN25 белый RTP",
    brand: "RTP",
    quantity: "30/10 шт",
    price: 94,
    unit: "шт",
    category: "troynikPPR",
    categoryName: "Тройник ППР",
    allResidual: 0,
    residualValue: "",
    isActive: false,
  },

  // ═══════════════════════════════════════════════════════════
  // 6. kranPPR — Краны шаровые + Вентили 
  // ═══════════════════════════════════════════════════════════
  {
    id: 59,
    img: kranPPR,
    name: "Кран шаровой СТпрох PPR 20ф PN25 белый RTP",
    brand: "RTP",
    quantity: "60/1 шт",
    price: 140,
    unit: "шт",
    category: "kranPPR",
    categoryName: "Кран ППР",
    allResidual: 0,
    residualValue: "",
    isActive: false,
  },
  {
    id: 60,
    img: kranPPR,
    name: "Кран шаровой ПЛпрох PPR 20ф PN25 белый RTP",
    brand: "RTP",
    quantity: "50/1 шт",
    price: 155,
    unit: "шт",
    category: "kranPPR",
    categoryName: "Кран ППР",
    allResidual: 0,
    residualValue: "",
    isActive: false,
  },
  {
    id: 61,
    img: kranPPR,
    name: "Кран шаровой СТпрох PPR 25ф PN25 белый RTP",
    brand: "RTP",
    quantity: "40/1 шт",
    price: 200,
    unit: "шт",
    category: "kranPPR",
    categoryName: "Кран ППР",
    allResidual: 1640,
    residualValue: "",
    isActive: true,
  },
  {
    id: 62,
    img: kranPPR,
    name: "Кран шаровой ПЛпрох PPR 25ф PN25 белый RTP",
    brand: "RTP",
    quantity: "30/1 шт",
    price: 240,
    unit: "шт",
    category: "kranPPR",
    categoryName: "Кран ППР",
    allResidual: 0,
    residualValue: "",
    isActive: false,
  },
  {
    id: 63,
    img: kranPPR,
    name: "Кран шаровой СТпрох PPR 32ф PN25 белый RTP",
    brand: "RTP",
    quantity: "20/1 шт",
    price: 310,
    unit: "шт",
    category: "kranPPR",
    categoryName: "Кран ППР",
    allResidual: 0,
    residualValue: "",
    isActive: false,
  },
  {
    id: 64,
    img: kranPPR,
    name: "Кран шаровой ПЛпрох PPR 32ф PN25 белый RTP",
    brand: "RTP",
    quantity: "20/1 шт",
    price: 350,
    unit: "шт",
    category: "kranPPR",
    categoryName: "Кран ППР",
    allResidual: 0,
    residualValue: "",
    isActive: false,
  },
  {
    id: 65,
    img: kranPPR,
    name: "Кран шаровой СТпрох PPR 40ф PN25 белый RTP",
    brand: "RTP",
    quantity: "20/1 шт",
    price: 680,
    unit: "шт",
    category: "kranPPR",
    categoryName: "Кран ППР",
    allResidual: 0,
    residualValue: "",
    isActive: false,
  },
  {
    id: 66,
    img: kranPPR,
    name: "Кран шаровой СТпрох PPR 50ф PN25 белый RTP",
    brand: "RTP",
    quantity: "6/1 шт",
    price: 880,
    unit: "шт",
    category: "kranPPR",
    categoryName: "Кран ППР",
    allResidual: 0,
    residualValue: "",
    isActive: false,
  },
  {
    id: 67,
    img: kranPPR,
    name: "Кран шаровой СТпрох PPR 63ф PN25 белый RTP",
    brand: "RTP",
    quantity: "4/1 шт",
    price: 1400,
    unit: "шт",
    category: "kranPPR",
    allResidual: 16,
    residualValue: "",
    isActive: true,
  },

  {
    id: 68,
    img: kranPPRRdPr,
    name: "Кран шаровой для радиатора PPR прямой 20х1\\2ф PN25 белый RTP",
    brand: "RTP",
    quantity: "50/1 шт",
    price: 330,
    unit: "шт",
    category: "kranPPR",
    categoryName: "Кран ППР",
    allResidual: 1000,
    residualValue: "",
    isActive: true,
  },
  {
    id: 69,
    img: kranPPRRdUg,
    name: "Кран шаровой для радиатора PPR угловой 20х1\\2ф PN25 белый RTP",
    brand: "RTP",
    quantity: "50/1 шт",
    price: 330,
    unit: "шт",
    category: "kranPPR",
    categoryName: "Кран ППР",
    allResidual: 0,
    residualValue: "",
    isActive: false,
  },
  {
    id: 70,
    img: kranPPRRdPr,
    name: "Кран шаровой для радиатора PPR прямой 25х3\\4ф PN25 белый RTP",
    brand: "RTP",
    quantity: "40/1 шт",
    price: 385,
    unit: "шт",
    category: "kranPPR",
    categoryName: "Кран ППР",
    allResidual: 0,
    residualValue: "",
    isActive: false,
  },
  {
    id: 71,
    img: kranPPRRdUg,
    name: "Кран шаровой для радиатора PPR угловой 25х3\\4ф PN25 белый RTP",
    brand: "RTP",
    quantity: "40/1 шт",
    price: 385,
    unit: "шт",
    category: "kranPPR",
    allResidual: 1050,
    residualValue: "",
    isActive: true,
  },
  
  {
    id: 72,
    img: vintelPPR,
    name: "Вентиль 90° в сборе ВН\\ВН PPR 20ф PN25 белый RTP",
    brand: "RTP",
    quantity: "40/10 шт",
    price: 350,
    unit: "шт",
    category: "kranPPR",
    categoryName: "Кран ППР",
    allResidual: 1400,
    residualValue: "",
    isActive: true,
  },
  {
    id: 73,
    img: vintelPPR,
    name: "Вентиль 90° в сборе ВН\\ВН PPR 25ф PN25 белый RTP",
    brand: "RTP",
    quantity: "25/5 шт",
    price: 380,
    unit: "шт",
    category: "kranPPR",
    categoryName: "Кран ППР",
    categoryName: "Кран ППР",
    allResidual: 275,
    residualValue: "",
    isActive: true,
  },
  {
    id: 74,
    img: vintelPPR,
    name: "Вентиль 90° в сборе ВН\\ВН PPR 32ф PN25 белый RTP",
    brand: "RTP",
    quantity: "15/5 шт",
    price: 410,
    unit: "шт",
    category: "kranPPR",
    allResidual: 135,
    residualValue: "",
    isActive: true,
  },

  // ═══════════════════════════════════════════════════════════
  // 7. muftaKombPPR — Муфта комбинированная + Американка
  // ═══════════════════════════════════════════════════════════
  {
    id: 75,
    img: muftaPPRKbVr,
    name: "Муфта комбинированная с В\\Р PPR 20х1\\2ф PN25 белый RTP",
    brand: "RTP",
    quantity: "150/25 шт",
    price: 62,
    unit: "шт",
    category: "muftaKombPPR",
    categoryName: "Муфта комб ППР",
    allResidual: 0,
    residualValue: "",
    isActive: false,
  },
  {
    id: 76,
    img: muftaPPRKbVr,
    name: "Муфта комбинированная с В\\Р PPR 20х3\\4ф PN25 белый RTP",
    brand: "RTP",
    quantity: "90/15 шт",
    price: 100,
    unit: "шт",
    category: "muftaKombPPR",
    categoryName: "Муфта комб ППР",
    allResidual: 0,
    residualValue: "",
    isActive: false,
  },
  {
    id: 77,
    img: muftaPPRKbNr,
    name: "Муфта комбинированная с Н\\Р PPR 20х1\\2ф PN25 белый RTP",
    brand: "RTP",
    quantity: "150/25 шт",
    price: 68,
    unit: "шт",
    category: "muftaKombPPR",
    categoryName: "Муфта комб ППР",
    allResidual: 9900,
    residualValue: "",
    isActive: true,
  },
  {
    id: 78,
    img: muftaPPRKbNr,
    name: "Муфта комбинированная с Н\\Р PPR 20х3\\4ф PN25 белый RTP",
    brand: "RTP",
    quantity: "90/15 шт",
    price: 110,
    unit: "шт",
    category: "muftaKombPPR",
    allResidual: 0,
    residualValue: "",
    isActive: false,
  },
  {
    id: 79,
    img: muftaPPRKbVr,
    name: "Муфта комбинированная с В\\Р PPR 25х3\\4ф PN25 белый RTP",
    brand: "RTP",
    quantity: "120/20 шт",
    price: 75,
    unit: "шт",
    category: "muftaKombPPR",
    categoryName: "Муфта комб ППР",
    allResidual: 0,
    residualValue: "",
    isActive: false,
  },
  {
    id: 80,
    img: muftaPPRKbNr,
    name: "Муфта комбинированная с Н\\Р PPR 25х3\\4ф PN25 белый RTP",
    brand: "RTP",
    quantity: "80/20 шт",
    price: 83,
    unit: "шт",
    category: "muftaKombPPR",
    categoryName: "Муфта комб ППР",
    allResidual: 0,
    residualValue: "",
    isActive: false,
  },
  {
    id: 81,
    img: muftaPPRKbVr,
    name: "Муфта комбинированная с В\\Р PPR 32х1ф PN25 белый RTP",
    brand: "RTP",
    quantity: "60/15 шт",
    price: 127,
    unit: "шт",
    category: "muftaKombPPR",
    categoryName: "Муфта комб ППР",
    allResidual: 0,
    residualValue: "",
    isActive: false,
  },
  {
    id: 82,
    img: muftaPPRKbNr,
    name: "Муфта комбинированная с Н\\Р PPR 32х1ф PN25 белый RTP",
    brand: "RTP",
    quantity: "60/15 шт",
    price: 154,
    unit: "шт",
    category: "muftaKombPPR",
    categoryName: "Муфта комб ППР",
    allResidual: 0,
    residualValue: "",
    isActive: false,
  },
  {
    id: 83,
    img: muftaPPRKbVr,
    name: "Муфта комбинированная с В\\Р PPR 40х1 1\\4ф PN25 белый RTP",
    brand: "RTP",
    quantity: "36/6 шт",
    price: 375,
    unit: "шт",
    category: "muftaKombPPR",
    categoryName: "Муфта комб ППР",
    allResidual: 0,
    residualValue: "",
    isActive: false,
  },
  {
    id: 84,
    img: muftaPPRKbNr,
    name: "Муфта комбинированная с Н\\Р PPR 40х1 1\\4ф PN25 белый RTP",
    brand: "RTP",
    quantity: "48/6 шт",
    price: 500,
    unit: "шт",
    category: "muftaKombPPR",
    categoryName: "Муфта комб ППР",
    allResidual: 0,
    residualValue: "",
    isActive: false,
  },
  {
    id: 85,
    img: muftaPPRKbVr,
    name: "Муфта комбинированная с В\\Р PPR 50х1 1\\2ф PN25 белый RTP",
    brand: "RTP",
    quantity: "24/2 шт",
    price: 400,
    unit: "шт",
    category: "muftaKombPPR",
    categoryName: "Муфта комб ППР",
    allResidual: 0,
    residualValue: "",
    isActive: false,
  },
  {
    id: 86,
    img: muftaPPRKbNr,
    name: "Муфта комбинированная с Н\\Р PPR 50х1 1\\2ф PN25 белый RTP",
    brand: "RTP",
    quantity: "22/2 шт",
    price: 580,
    unit: "шт",
    category: "muftaKombPPR",
    categoryName: "Муфта комб ППР",
    allResidual: 0,
    residualValue: "",
    isActive: false,
  },
  // razyom ppr rtp

  {
    id: 87,
    img: muftaPPRAmrVr,
    name: "Муфта комбинированная разъемная (американка) с В\\Р PPR 20х1\\2 PN25 белый RTP",
    brand: "RTP",
    quantity: "200/20 шт",
    price: 148,
    unit: "шт",
    category: "muftaKombPPR",
    categoryName: "Муфта комб ППР",
    allResidual: 0,
    residualValue: "",
    isActive: false,
  },
  {
    id: 88,
    img: muftaPPRAmrNr,
    name: "Муфта комбинированная разъемная (американка) с Н\\Р PPR 20х1\\2 PN25 белый RTP",
    brand: "RTP",
    quantity: "200/20 шт",
    price: 155,
    unit: "шт",
    category: "muftaKombPPR",
    categoryName: "Муфта комб ППР",
    allResidual: 0,
    residualValue: "",
    isActive: false,
  },
  {
    id: 89,
    img: muftaPPRAmrVr,
    name: "Муфта комбинированная разъемная (американка) с В\\Р PPR 20х3\\4 PN25 белый RTP",
    brand: "RTP",
    quantity: "200/20 шт",
    price: 143,
    unit: "шт",
    category: "muftaKombPPR",
    categoryName: "Муфта комб ППР",
    allResidual: 0,
    residualValue: "",
    isActive: false,
  },
  {
    id: 90,
    img: muftaPPRAmrNr,
    name: "Муфта комбинированная разъемная (американка) с Н\\Р PPR 20х3\\4 PN25 белый RTP",
    brand: "RTP",
    quantity: "200/20 шт",
    price: 154,
    unit: "шт",
    category: "muftaKombPPR",
    categoryName: "Муфта комб ППР",
    allResidual: 0,
    residualValue: "",
    isActive: false,
  },
  {
    id: 91,
    img: muftaPPRAmrNr,
    name: "Муфта комбинированная разъемная (американка) с Н\\Р PPR 20х1 PN25 белый RTP",
    brand: "RTP",
    quantity: "100/10 шт",
    price: 270,
    unit: "шт",
    category: "muftaKombPPR",
    categoryName: "Муфта комб ППР",
    allResidual: 0,
    residualValue: "",
    isActive: false,
  },
  {
    id: 92,
    img: muftaPPRAmrVr,
    name: "Муфта комбинированная разъемная (американка) с В\\Р PPR 25х3\\4 PN25 белый RTP",
    brand: "RTP",
    quantity: "140/10 шт",
    price: 180,
    unit: "шт",
    category: "muftaKombPPR",
    categoryName: "Муфта комб ППР",
    allResidual: 0,
    residualValue: "",
    isActive: false,
  },
  {
    id: 93,
    img: muftaPPRAmrNr,
    name: "Муфта комбинированная разъемная (американка) с Н\\Р PPR 25х3\\4 PN25 белый RTP",
    brand: "RTP",
    quantity: "120/10 шт",
    price: 198,
    unit: "шт",
    category: "muftaKombPPR",
    categoryName: "Муфта комб ППР",
    allResidual: 0,
    residualValue: "",
    isActive: false,
  },
  {
    id: 94,
    img: muftaPPRAmrNr,
    name: "Муфта комбинированная разъемная (американка) с Н\\Р PPR 25х1 PN25 белый RTP",
    brand: "RTP",
    quantity: "100/10 шт",
    price: 240,
    unit: "шт",
    category: "muftaKombPPR",
    categoryName: "Муфта комб ППР",
    allResidual: 0,
    residualValue: "",
    isActive: false,
  },
  {
    id: 95,
    img: muftaPPRAmrVr,
    name: "Муфта комбинированная разъемная (американка) с В\\Р PPR 32х1 PN25 белый RTP",
    brand: "RTP",
    quantity: "90/10 шт",
    price: 277,
    unit: "шт",
    category: "muftaKombPPR",
    categoryName: "Муфта комб ППР",
    allResidual: 0,
    residualValue: "",
    isActive: false,
  },
  {
    id: 96,
    img: muftaPPRAmrNr,
    name: "Муфта комбинированная разъемная (американка) с Н\\Р PPR 32х1 PN25 белый RTP",
    brand: "RTP",
    quantity: "80/10 шт",
    price: 320,
    unit: "шт",
    category: "muftaKombPPR",
    categoryName: "Муфта комб ППР",
    allResidual: 0,
    residualValue: "",
    isActive: false,
  },
  {
    id: 97,
    img: muftaPPRAmrVr,
    name: "Муфта комбинированная разъемная (американка) с В\\Р PPR 40х1 1\\4 PN25 белый RTP",
    brand: "RTP",
    quantity: "50/5 шт",
    price: 418,
    unit: "шт",
    category: "muftaKombPPR",
    categoryName: "Муфта комб ППР",
    allResidual: 0,
    residualValue: "",
    isActive: false,
  },
  {
    id: 98,
    img: muftaPPRAmrNr,
    name: "Муфта комбинированная разъемная (американка) с Н\\Р PPR 40х1 1\\4 PN25 белый RTP",
    brand: "RTP",
    quantity: "40/5 шт",
    price: 495,
    unit: "шт",
    category: "muftaKombPPR",
    categoryName: "Муфта комб ППР",
    allResidual: 0,
    residualValue: "",
    isActive: false,
  },
  {
    id: 99,
    img: muftaPPRAmrVr,
    name: "Муфта комбинированная разъемная (американка) с В\\Р PPR 50х1 1\\2 PN25 белый RTP",
    brand: "RTP",
    quantity: "24/4 шт",
    price: 550,
    unit: "шт",
    category: "muftaKombPPR",
    categoryName: "Муфта комб ППР",
    allResidual: 0,
    residualValue: "",
    isActive: false,
  },
  {
    id: 100,
    img: muftaPPRAmrNr,
    name: "Муфта комбинированная разъемная (американка) с Н\\Р PPR 50х1 1\\2 PN25 белый RTP",
    brand: "RTP",
    quantity: "20/2 шт",
    price: 650,
    unit: "шт",
    category: "muftaKombPPR",
    categoryName: "Муфта комб ППР",
    allResidual: 0,
    residualValue: "",
    isActive: false,
  },

  // ═══════════════════════════════════════════════════════════
  // 8. ugolKrepPPR — Угол ком п\смес + Угольник с креплением
  // ═══════════════════════════════════════════════════════════
  {
    id: 101,
    img: ugolVrRTP,
    name: "Угольник с креплением PPR В\\Р 20х1\\2 PN25 белый RTP",
    brand: "RTP",
    quantity: "75/25 шт",
    price: 72,
    unit: "шт",
    category: "ugolKrepPPR",
    categoryName: "Угол креп ППР",
    allResidual: 0,
    residualValue: "",
    isActive: false,
  },
  {
    id: 102,
    img: ugolNrRTP,
    name: "Угольник с креплением PPR Н\\Р 20х1\\2 PN25 белый RTP",
    brand: "RTP",
    quantity: "75/25 шт",
    price: 77,
    unit: "шт",
    category: "ugolKrepPPR",
    categoryName: "Угол креп ППР",
    allResidual: 2250,
    residualValue: "",
    isActive: true,
  },
  {
    id: 103,
    img: ugolVrRTP,
    name: "Угольник с креплением PPR В\\Р 25х1\\2 PN25 белый RTP",
    brand: "RTP",
    quantity: "60/20 шт",
    price: 72,
    unit: "шт",
    category: "ugolKrepPPR",
    categoryName: "Угол креп ППР",
    allResidual: 0,
    residualValue: "",
    isActive: false,
  },
  {
    id: 104,
    img: ugolNrRTP,
    name: "Угольник с креплением PPR Н\\Р 25х1\\2 PN25 белый RTP",
    brand: "RTP",
    quantity: "60/20 шт",
    price: 83,
    unit: "шт",
    category: "ugolKrepPPR",
    categoryName: "Угол креп ППР",
    allResidual: 0,
    residualValue: "",
    isActive: false,
  },
  {
    id: 105,
    img: shablonVr,
    name: "Угол ком п\\смес PPR В\\Р 20х1\\2 PN25 белый RTP",
    brand: "RTP",
    quantity: "24/8 шт",
    price: 120,
    unit: "шт",
    category: "ugolKrepPPR",
    categoryName: "Угол креп ППР",
    allResidual: 0,
    residualValue: "",
    isActive: false,
  },
  {
    id: 106,
    img: shablonNr,
    name: "Угол ком п\\смес PPR Н\\Р 20х3\\4 PN25 белый RTP",
    brand: "RTP",
    quantity: "20/5 шт",
    price: 220,
    unit: "шт",
    category: "ugolKrepPPR",
    categoryName: "Угол креп ППР",
    allResidual: 0,
    residualValue: "",
    isActive: false,
  },
  {
    id: 107,
    img: shablonNr,
    name: "Угол ком п\\смес PPR Н\\Р 20х1\\2 PN25 белый RTP",
    brand: "RTP",
    quantity: "24/6 шт",
    price: 120,
    unit: "шт",
    category: "ugolKrepPPR",
    categoryName: "Угол креп ППР",
    allResidual: 0,
    residualValue: "",
    isActive: false,
  },
  {
    id: 108,
    img: shablonNr,
    name: "Угол ком п\\смес PPR Н\\Р 25х1\\2 PN25 белый RTP",
    brand: "RTP",
    quantity: "18/6 шт",
    price: 125,
    unit: "шт",
    category: "ugolKrepPPR",
    categoryName: "Угол креп ППР",
    allResidual: 0,
    residualValue: "",
    isActive: false,
  },

  // ═══════════════════════════════════════════════════════════
  // 9. drugoyPPR — Прочие PPR фитинги (Опора, Обводное колено, Заглушка)
  // ═══════════════════════════════════════════════════════════
  {
    id: 109,
    img: oporaPPR,
    name: "Опора с защелкой PPR 20ф PN25 белый RTP",
    brand: "RTP",
    quantity: "360/60 шт",
    price: 4,
    unit: "шт",
    category: "drugoyPPR",
    categoryName: "Другой ППР",
    allResidual: 0,
    residualValue: "",
    isActive: false,
  },
  {
    id: 111,
    img: oporaPPR,
    name: "Опора с защелкой PPR 25ф PN25 серый RTP",
    brand: "RTP",
    quantity: "240/40 шт",
    price: 5,
    unit: "шт",
    category: "drugoyPPR",
    categoryName: "Другой ППР",
    allResidual: 0,
    residualValue: "",
    isActive: false,
  },
  {
    id: 112,
    img: oporaPPR,
    name: "Опора с защелкой PPR 32ф PN25 белый RTP",
    brand: "RTP",
    quantity: "210/35 шт",
    price: 7,
    unit: "шт",
    category: "drugoyPPR",
    categoryName: "Другой ППР",
    allResidual: 3990,
    residualValue: "",
    isActive: true,
  },
  {
    id: 113,
    img: oporaPPR,
    name: "Опора с защелкой PPR 40ф PN25 белый RTP",
    brand: "RTP",
    quantity: "100/25 шт",
    price: 9,
    unit: "шт",
    category: "drugoyPPR",
    categoryName: "Другой ППР",
    allResidual: 0,
    residualValue: "",
    isActive: false,
  },
  {
    id: 114,
    img: mostikPPR,
    name: "Обводное колено с муфтой PPR 20ф PN25 белый RTP",
    brand: "RTP",
    quantity: "120/20 шт",
    price: 16,
    unit: "шт",
    category: "drugoyPPR",
    categoryName: "Другой ППР",
    allResidual: 80000,
    residualValue: "",
    isActive: true,
  },
  {
    id: 115,
    img: mostikPPR,
    name: "Обводное колено с муфтой PPR 25ф PN25 белый RTP",
    brand: "RTP",
    quantity: "140/20 шт",
    price: 22,
    unit: "шт",
    category: "drugoyPPR",
    categoryName: "Другой ППР",
    allResidual: 0,
    residualValue: "",
    isActive: false,
  },
  {
    id: 116,
    img: mostikPPR,
    name: "Обводное колено с муфтой PPR 32ф PN25 белый RTP",
    brand: "RTP",
    quantity: "70/10 шт",
    price: 44,
    unit: "шт",
    category: "drugoyPPR",
    categoryName: "Другой ППР",
    allResidual: 350,
    residualValue: "",
    isActive: true,
  },
  {
    id: 117,
    img: obratniKlapn,
    name: "Обратный клапан 20ф PN25 белый RTP",
    brand: "RTP",
    quantity: "240/20 шт",
    price: 110,
    unit: "шт",
    category: "drugoyPPR",
    categoryName: "Другой ППР",
    allResidual: 0,
    residualValue: "",
    isActive: false,
  },
  {
    id: 118,
    img: obratniKlapn,
    name: "Обратный клапан 25ф PN25 белый RTP",
    brand: "RTP",
    quantity: "60/20 шт",
    price: 135,
    unit: "шт",
    category: "drugoyPPR",
    categoryName: "Другой ППР",
    allResidual: 0,
    residualValue: "",
    isActive: false,
  },
  {
    id: 119,
    img: obratniKlapn,
    name: "Обратный клапан 32ф PN25 белый RTP",
    brand: "RTP",
    quantity: "120/12 шт",
    price: 200,
    unit: "шт",
    category: "drugoyPPR",
    categoryName: "Другой ППР",
    allResidual: 0,
    residualValue: "",
    isActive: false,
  },
  {
    id: 120,
    img: zagulushkaPPR,
    name: "Заглушка PPR 20ф PN25 белый RTP",
    brand: "RTP",
    quantity: "390/65 шт",
    price: 6,
    unit: "шт",
    category: "drugoyPPR",
    categoryName: "Другой ППР",
    allResidual: 0,
    residualValue: "",
    isActive: false,
  },
  {
    id: 121,
    img: zagulushkaPPR,
    name: "Заглушка PPR 25ф PN25 белый RTP",
    brand: "RTP",
    quantity: "240/40 шт",
    price: 8,
    unit: "шт",
    category: "drugoyPPR",
    categoryName: "Другой ППР",
    allResidual: 4080,
    residualValue: "",
    isActive: true,
  },
  {
    id: 122,
    img: zagulushkaPPR,
    name: "Заглушка PPR 32ф PN25 белый RTP",
    brand: "RTP",
    quantity: "160/40 шт",
    price: 11,
    unit: "шт",
    category: "drugoyPPR",
    categoryName: "Другой ППР",
    allResidual: 0,
    residualValue: "",
    isActive: false,
  },
  {
    id: 123,
    img: zagulushkaPPR,
    name: "Заглушка PPR 40ф PN25 белый RTP",
    brand: "RTP",
    quantity: "90/15 шт",
    price: 22,
    unit: "шт",
    category: "drugoyPPR",
    categoryName: "Другой ППР",
    allResidual: 0,
    residualValue: "",
    isActive: false,
  },

  // ═══════════════════════════════════════════════════════════
  // 10. trubaPERT — Труба PERT (тёплый пол) + Скобы
  // ═══════════════════════════════════════════════════════════
  {
    id: 124,
    img: toplipolRTP,
    name: "Труба PERT 16х2.0х100 красный RTP",
    brand: "RTP",
    quantity: "100м",
    price: 29,
    unit: "м",
    category: "trubaPERT",
    categoryName: "Труба PERT",
    allResidual: 0,
    residualValue: "",
    isActive: false,
  },
  {
    id: 125,
    img: toplipolRTP,
    name: "Труба PERT 16х2.0х200 красный RTP",
    brand: "RTP",
    quantity: "200м",
    price: 29,
    unit: "м",
    category: "trubaPERT",
    categoryName: "Труба PERT",
    allResidual: 0,
    residualValue: "",
    isActive: false,
  },
  {
    id: 126,
    img: toplipolRTP,
    name: "Труба PERT 16х2.0х600 красный RTP",
    brand: "RTP",
    quantity: "600м",
    price: 29,
    unit: "м",
    category: "trubaPERT",
    categoryName: "Труба PERT",
    allResidual: 0,
    residualValue: "",
    isActive: false,
  },
  {
    id: 127,
    img: toplipolRTPSer,
    name: "Труба PERT 16х2.0х100 серый RTP",
    brand: "RTP",
    quantity: "100м",
    price: 29,
    unit: "м",
    category: "trubaPERT",
    categoryName: "Труба PERT",
    allResidual: 0,
    residualValue: "",
    isActive: false,
  },
  {
    id: 128,
    img: toplipolRTPSer,
    name: "Труба PERT 16х2.0х200 серый RTP",
    brand: "RTP",
    quantity: "200м",
    price: 29,
    unit: "м",
    category: "trubaPERT",
    categoryName: "Труба PERT",
    allResidual: 0,
    residualValue: "",
    isActive: false,
  },
  {
    id: 129,
    img: toplipolRTP,
    name: "Труба PERT 20х2.0х200 красный RTP",
    brand: "RTP",
    quantity: "200м",
    price: 40,
    unit: "м",
    category: "trubaPERT",
    categoryName: "Труба PERT",
    allResidual: 0,
    residualValue: "",
    isActive: false,
  },
  {
    id: 130,
    img: skobaRTP,
    name: "Длинные скобы для теплого пола (16-20) RTP",
    brand: "RTP",
    quantity: "1000 шт",
    price: 2.5,
    unit: "шт",
    category: "trubaPERT",
    categoryName: "Труба PERT",
    allResidual: 120000,
    residualValue: "",
    isActive: true,
  },
  {
    id: 333333,
    img: mentalaplast,
    name: "Труба металлопластиковая PERT-AL-PERT 16х2,0х200, белый, РТП",
    brand: "RTP",
    quantity: "200м",
    price: 90,
    allResidual: 2000,
    residualValue: "",
    isActive: true,
    unit: "м",
    category: "other",
  },

  // ═══════════════════════════════════════════════════════════
  // 11. trubaVK — Трубы ВК (внутренняя канализация, серый)
  // ═══════════════════════════════════════════════════════════
  {
    id: 131,
    img: trubaVkRTP50,
    name: "Труба ВК ПП 50х1,8х250 серый RTP",
    brand: "RTP",
    quantity: "125 шт",
    price: 50,
    unit: "шт",
    category: "trubaVK",
    categoryName: "Труба ВК",
    allResidual: 0,
    residualValue: "",
    isActive: false,
  },
  {
    id: 132,
    img: trubaVkRTP50,
    name: "Труба ВК ПП 50х1,8х500 серый RTP",
    brand: "RTP",
    quantity: "60 шт",
    price: 66,
    unit: "шт",
    category: "trubaVK",
    categoryName: "Труба ВК",
    allResidual: 720,
    residualValue: "",
    isActive: true,
  },
  {
    id: 133,
    img: trubaVkRTP50,
    name: "Труба ВК ПП 50х1,8х1000 серый RTP",
    brand: "RTP",
    quantity: "10 шт",
    price: 105,
    unit: "шт",
    category: "trubaVK",
    categoryName: "Труба ВК",
    allResidual: 0,
    residualValue: "",
    isActive: false,
    
  },
  {
    id: 134,
    img: trubaVkRTP50,
    name: "Труба ВК ПП 50х1,8х2000 серый RTP",
    brand: "RTP",
    quantity: "10 шт",
    price: 176,
    unit: "шт",
    category: "trubaVK",
    categoryName: "Труба ВК",
    allResidual: 0,
    residualValue: "",
    isActive: false,
  },
  {
    id: 135,
    img: trubaVkRTP50,
    name: "Труба ВК ПП 50х1,8х3000 серый RTP",
    brand: "RTP",
    quantity: "10 шт",
    price: 264,
    unit: "шт",
    category: "trubaVK",
    categoryName: "Труба ВК",
    allResidual: 0,
    residualValue: "",
    isActive: false,
  },
  {
    id: 136,
    img: trubaVkRTP50,
    name: "Труба ВК ПП 76х2.7х1000 серый RTP",
    brand: "RTP",
    quantity: "10 шт",
    price: 180,
    unit: "шт",
    category: "trubaVK",
    categoryName: "Труба ВК",
    allResidual: 0,
    residualValue: "",
    isActive: false,
  },
  {
    id: 137,
    img: trubaVkRTP50,
    name: "Труба ВК ПП 76х2.7х2000 серый RTP",
    brand: "RTP",
    quantity: "10 шт",
    price: 330,
    unit: "шт",
    category: "trubaVK",
    categoryName: "Труба ВК",
    allResidual: 0,
    residualValue: "",
    isActive: false,
  },
  {
    id: 138,
    img: trubaVkRTP50,
    name: "Труба ВК ПП 76х2.7х3000 серый RTP",
    brand: "RTP",
    quantity: "10 шт",
    price: 495,
    unit: "шт",
    category: "trubaVK",
    categoryName: "Труба ВК",
    allResidual: 0,
    residualValue: "",
    isActive: false,
  },
  {
    id: 139,
    img: trubaVkRTP,
    name: "Труба ВК ПП 110х2.7х250 серый RTP",
    brand: "RTP",
    quantity: "28 шт",
    price: 145,
    unit: "шт",
    category: "trubaVK",
    categoryName: "Труба ВК",
    allResidual: 0,
    residualValue: "",
    isActive: false,
  },
  {
    id: 140,
    img: trubaVkRTP,
    name: "Труба ВК ПП 110х2.7х500 серый RTP",
    brand: "RTP",
    quantity: "10 шт",
    price: 223,
    unit: "шт",
    category: "trubaVK",
    categoryName: "Труба ВК",
    allResidual: 0,
    residualValue: "",
    isActive: false,
  },
  {
    id: 141,
    img: trubaVkRTP,
    name: "Труба ВК ПП 110х2.7х1000 серый RTP",
    brand: "RTP",
    quantity: "10 шт",
    price: 342,
    unit: "шт",
    category: "trubaVK",
    categoryName: "Труба ВК",
    allResidual: 0,
    residualValue: "",
    isActive: false,
  },
  {
    id: 142,
    img: trubaVkRTP,
    name: "Труба ВК ПП 110х2.7х2000 серый RTP",
    brand: "RTP",
    quantity: "10 шт",
    price: 605,
    unit: "шт",
    category: "trubaVK",
    categoryName: "Труба ВК",
    allResidual: 0,
    residualValue: "",
    isActive: false,
  },
  {
    id: 143,
    img: trubaVkRTP,
    name: "Труба ВК ПП 110х2.7х3000 серый RTP",
    brand: "RTP",
    quantity: "10 шт",
    price: 900,
    unit: "шт",
    category: "trubaVK",
    categoryName: "Труба ВК",
    allResidual: 0,
    residualValue: "",
    isActive: false,
  },

  // ═══════════════════════════════════════════════════════════
  // 12. trubaNK — Трубы НК (наружная канализация, рыжий)
  // ═══════════════════════════════════════════════════════════
  {
    id: 145,
    img: trubaNrRTP,
    name: "Труба НК ПП 110х3.4х500 рыжый RTP",
    brand: "RTP",
    quantity: "10 шт",
    price: 250,
    unit: "шт",
    category: "trubaNK",
    categoryName: "Труба НК",
    allResidual: 0,
    residualValue: "",
    isActive: false,
  },
  {
    id: 146,
    img: trubaNrRTP,
    name: "Труба НК ПП 110х3.4х1000 рыжый RTP",
    brand: "RTP",
    quantity: "10 шт",
    price: 380,
    unit: "шт",
    category: "trubaNK",
    categoryName: "Труба НК",
    allResidual: 0,
    residualValue: "",
    isActive: false,
  },
  {
    id: 147,
    img: trubaNrRTP,
    name: "Труба НК ПП 110х3.4х2000 рыжый RTP",
    brand: "RTP",
    quantity: "10 шт",
    price: 760,
    unit: "шт",
    category: "trubaNK",
    categoryName: "Труба НК",
    allResidual: 0,
    residualValue: "",
    isActive: false,
  },
  {
    id: 148,
    img: trubaNrRTP,
    name: "Труба НК ПП 110х3.4х3000 рыжый RTP",
    brand: "RTP",
    quantity: "10 шт",
    price: 1120,
    unit: "шт",
    category: "trubaNK",
    categoryName: "Труба НК",
    allResidual: 0,
    residualValue: "",
    isActive: false,
  },
  {
    id: 149,
    img: trubaNrRTP,
    name: "Труба НК ПП 160х4,9х500 рыжый RTP",
    brand: "RTP",
    quantity: "4 шт",
    price: 495,
    unit: "шт",
    category: "trubaNK",
    categoryName: "Труба НК",
    allResidual: 0,
    residualValue: "",
    isActive: false,
  },
  {
    id: 150,
    img: trubaNrRTP,
    name: "Труба НК ПП 160х4,9х1000 рыжый RTP",
    brand: "RTP",
    quantity: "2 шт",
    price: 890,
    unit: "шт",
    category: "trubaNK",
    categoryName: "Труба НК",
    allResidual: 0,
    residualValue: "",
    isActive: false,
  },
  {
    id: 151,
    img: trubaNrRTP,
    name: "Труба НК ПП 160х4,9х2000 рыжый RTP",
    brand: "RTP",
    quantity: "2 шт",
    price: 1800,
    unit: "шт",
    category: "trubaNK",
    allResidual: 0,
    residualValue: "",
    isActive: false,
  },
  {
    id: 152,
    img: trubaNrRTP,
    name: "Труба НК ПП 160х4,9х3000 рыжый RTP",
    brand: "RTP",
    quantity: "2 шт",
    price: 2510,
    unit: "шт",
    category: "trubaNK",
    categoryName: "Труба НК",
    allResidual: 0,
    residualValue: "",
    isActive: false,
  },

  // ═══════════════════════════════════════════════════════════
  // 13. fitingVK — Фитинги ВК (отводы, тройники, муфты, хомуты и др.)
  // ═══════════════════════════════════════════════════════════
  {
    id: 153,
    img: patrubkaVk110,
    name: "Потрубок компенсационный ВК ПП 110х87 К,серый RTP",
    brand: "RTP",
    quantity: "36 шт",
    price: 110,
    unit: "шт",
    category: "fitingVK",
    categoryName: "Фитинги ВК",
    allResidual: 216,
    residualValue: "",
    isActive: true,
  },
  {
    id: 154,
    img: patrubkaVk,
    name: "Потрубок компенсационный ВК ПП 50х87 К,серый RTP",
    brand: "RTP",
    quantity: "75 шт",
    price: 60,
    unit: "шт",
    category: "fitingVK",
    categoryName: "Фитинги ВК",
    allResidual: 0,
    residualValue: "",
    isActive: false,
  },
  {
    id: 155,
    img: patrubkaVkGip50,
    name: "Потрубок гофра ВК ПП 50х87 К,серый RTP",
    brand: "RTP",
    quantity: "60 шт",
    price: 60,
    unit: "шт",
    category: "fitingVK",
    allResidual: 0,
    residualValue: "",
    isActive: false,
  },
  {
    id: 156,
    img: otvod5045,
    name: "Отвод ВК ПП 50х45 К,серый RTP",
    brand: "RTP",
    quantity: "140 шт",
    price: 25,
    unit: "шт",
    category: "fitingVK",
    categoryName: "Фитинги ВК",
    allResidual: 0,
    residualValue: "",
    isActive: false,
  },
  {
    id: 157,
    img: otvod5087,
    name: "Отвод ВК ПП 50х87 К,серый RTP",
    brand: "RTP",
    quantity: "120 шт",
    price: 23,
    unit: "шт",
    category: "fitingVK",
    categoryName: "Фитинги ВК",
    allResidual: 0,
    residualValue: "",
    isActive: false,
  },
  {
    id: 158,
    img: otvod7545,
    name: "Отвод ВК ПП 75х45 К,серый RTP",
    brand: "RTP",
    quantity: "20 шт",
    price: 60,
    unit: "шт",
    category: "fitingVK",
    categoryName: "Фитинги ВК",
    allResidual: 0,
    residualValue: "",
    isActive: false,
  },
  {
    id: 159,
    img: otvod7587,
    name: "Отвод ВК ПП 75х87 К,серый RTP",
    brand: "RTP",
    quantity: "45 шт",
    price: 66,
    unit: "шт",
    category: "fitingVK",
    categoryName: "Фитинги ВК",
    allResidual: 0,
    residualValue: "",
    isActive: false,
  },
  {
    id: 160,
    img: otvod11087,
    name: "Отвод ВК ПП 110х87 К,серый RTP",
    brand: "RTP",
    quantity: "35 шт",
    price: 93,
    unit: "шт",
    category: "fitingVK",
    categoryName: "Фитинги ВК",
    allResidual: 0,
    residualValue: "",
    isActive: false,
  },
  {
    id: 161,
    img: otvod11045,
    name: "Отвод ВК ПП 110х45° К,серый RTP",
    brand: "RTP",
    quantity: "50 шт",
    price: 83,
    unit: "шт",
    category: "fitingVK",
    categoryName: "Фитинги ВК",
    allResidual: 0,
    residualValue: "",
    isActive: false,
  },
  {
    id: 162,
    img: otvod11015,
    name: "Отвод ВК ПП 110х15° К,серый RTP",
    brand: "RTP",
    quantity: "50 шт",
    price: 83,
    unit: "шт",
    category: "fitingVK",
    categoryName: "Фитинги ВК",
    allResidual: 0,
    residualValue: "",
    isActive: false,
  },
  {
    id: 163,
    img: otvod11030,
    name: "Отвод ВК ПП 110х30° К,серый RTP",
    brand: "RTP",
    quantity: "50 шт",
    price: 83,
    unit: "шт",
    category: "fitingVK",
    categoryName: "Фитинги ВК",
    allResidual: 0,
    residualValue: "",
    isActive: false,
  },
  {
    id: 164,
    img: otvod11067,
    name: "Отвод ВК ПП 110х67° К,серый RTP",
    brand: "RTP",
    quantity: "42 шт",
    price: 83,
    unit: "шт",
    category: "fitingVK",
    categoryName: "Фитинги ВК",
    allResidual: 0,
    residualValue: "",
    isActive: false,
  },

  // traynik vk
  {
    id: 165,
    img: traynikVk505045,
    name: "Тройник ВК ПП 50\\50\\45° К,серый RTP",
    brand: "RTP",
    quantity: "60 шт",
    price: 55,
    unit: "шт",
    category: "fitingVK",
    categoryName: "Фитинги ВК",
    allResidual: 0,
    residualValue: "",
    isActive: false,
  },
  {
    id: 166,
    img: traynikVk505087,
    name: "Тройник ВК ПП 50\\50\\87° К,серый RTP",
    brand: "RTP",
    quantity: "75 шт",
    price: 55,
    unit: "шт",
    category: "fitingVK",
    categoryName: "Фитинги ВК",
    allResidual: 0,
    residualValue: "",
    isActive: false,
  },
  {
    id: 167,
    img: traynik757545,
    name: "Тройник ВК ПП 75\\50\\45° К,серый RTP",
    brand: "RTP",
    quantity: "35 шт",
    price: 88,
    unit: "шт",
    category: "fitingVK",
    categoryName: "Фитинги ВК",
    allResidual: 0,
    residualValue: "",
    isActive: false,
  },
  {
    id: 168,
    img: traynik757587,
    name: "Тройник ВК ПП 75\\50\\87° К,серый RTP",
    brand: "RTP",
    quantity: "40 шт",
    price: 88,
    unit: "шт",
    category: "fitingVK",
    categoryName: "Фитинги ВК",
    allResidual: 0,
    residualValue: "",
    isActive: false,
  },
  {
    id: 169,
    img: traynik757545,
    name: "Тройник ВК ПП 75\\75\\45° К,серый RTP",
    brand: "RTP",
    quantity: "25 шт",
    price: 88,
    unit: "шт",
    category: "fitingVK",
    categoryName: "Фитинги ВК",
    allResidual: 150,
    residualValue: "",
    isActive: true,
  },
  {
    id: 170,
    img: traynik757587,
    name: "Тройник ВК ПП 75\\75\\87° К,серый RTP",
    brand: "RTP",
    quantity: "28 шт",
    price: 88,
    unit: "шт",
    category: "fitingVK",
    categoryName: "Фитинги ВК",
    allResidual: 0,
    residualValue: "",
    isActive: false,
  },
  {
    id: 171,
    img: traynik11011087,
    name: "Тройник ВК ПП 110\\110\\87° К,серый RTP",
    brand: "RTP",
    quantity: "32 шт",
    price: 150,
    unit: "шт",
    category: "fitingVK",
    categoryName: "Фитинги ВК",
    allResidual: 384,
    residualValue: "",
    isActive: true,
  },
  {
    id: 172,
    img: traynik11011045,
    name: "Тройник ВК ПП 110\\110\\45° К,серый RTP",
    brand: "RTP",
    quantity: "24 шт",
    price: 160,
    unit: "шт",
    category: "fitingVK",
    categoryName: "Фитинги ВК",
    allResidual: 0,
    residualValue: "",
    isActive: false,
  },
  {
    id: 173,
    img: traynik1105087,
    name: "Тройник ВК ПП 110\\50\\87° К,серый RTP",
    brand: "RTP",
    quantity: "54 шт",
    price: 105,
    unit: "шт",
    category: "fitingVK",
    categoryName: "Фитинги ВК",
    allResidual: 0,
    residualValue: "",
    isActive: false,
  },
  {
    id: 174,
    img: traynik1105045,
    name: "Тройник ВК ПП 110\\50\\45° К,серый RTP",
    brand: "RTP",
    quantity: "45 шт",
    price: 110,
    unit: "шт",
    category: "fitingVK",
    categoryName: "Фитинги ВК",
    allResidual: 0,
    residualValue: "",
    isActive: false,
  },
  {
    id: 175,
    img: traynik1105087,
    name: "Тройник ВК ПП 110\\76\\87° К,серый RTP",
    brand: "RTP",
    quantity: "15 шт",
    price: 150,
    unit: "шт",
    category: "fitingVK",
    categoryName: "Фитинги ВК",
    allResidual: 0,
    residualValue: "",
    isActive: false,
  },
  {
    id: 176,
    img: traynik1107545,
    name: "Тройник ВК ПП 110\\76\\45° К,серый RTP",
    brand: "RTP",
    quantity: "15 шт",
    price: 160,
    unit: "шт",
    category: "fitingVK",
    categoryName: "Фитинги ВК",
    allResidual: 0,
    residualValue: "",
    isActive: false,
  },

  // revizya vk
  {
    id: 177,
    img: reviziyaVk,
    name: "Ревизия с крышкой НК ПП 50х87° К,серый RTP",
    brand: "RTP",
    quantity: "80 шт",
    price: 90,
    unit: "шт",
    category: "fitingVK",
    categoryName: "Фитинги ВК",
    allResidual: 0,
    residualValue: "",
    isActive: false,
  },
  {
    id: 178,
    img: reviziyaVk,
    name: "Ревизия с крышкой НК ПП 76х87° К,серый RTP",
    brand: "RTP",
    quantity: "10 шт",
    price: 130,
    unit: "шт",
    category: "fitingVK",
    categoryName: "Фитинги ВК",
    allResidual: 0,
    residualValue: "",
    isActive: false,
  },
  {
    id: 179,
    img: reviziyaVk,
    name: "Ревизия с крышкой НК ПП 110х87° К,серый RTP",
    brand: "RTP",
    quantity: "36 шт",
    price: 170,
    unit: "шт",
    category: "fitingVK",
    categoryName: "Фитинги ВК",
    allResidual: 208,
    residualValue: "",
    isActive: true,
  },
  // zagulishka
  {
    id: 180,
    img: zagulushkaVk,
    name: "Заглушка ВК ПП 110х87° К,серый RTP",
    brand: "RTP",
    quantity: "140 шт",
    price: 30,
    unit: "шт",
    category: "fitingVK",
    categoryName: "Фитинги ВК",
    allResidual: 0,
    residualValue: "",
    isActive: false,
  },
  {
    id: 181,
    img: zagulushkaVk,
    name: "Заглушка ВК ПП 76х87° К,серый RTP",
    brand: "RTP",
    quantity: "90 шт",
    price: 25,
    unit: "шт",
    category: "fitingVK",
    categoryName: "Фитинги ВК",
    allResidual: 0,
    residualValue: "",
    isActive: false,
  },
  {
    id: 182,
    img: zagulushkaVk,
    name: "Заглушка ВК ПП 50х87° К,серый RTP",
    brand: "RTP",
    quantity: "200 шт",
    price: 15,
    unit: "шт",
    category: "fitingVK",
    categoryName: "Фитинги ВК",
    allResidual: 1000,
    residualValue: "",
    isActive: true,
  },

  //mufta
  {
    id: 183,
    img: muftaVk75,
    name: "Муфта двухраструбная ВК ПП 50х87° К,серый RTP",
    brand: "RTP",
    quantity: "150 шт",
    price: 30,
    unit: "шт",
    category: "fitingVK",
    categoryName: "Фитинги ВК",
    allResidual: 0,
    residualValue: "",
    isActive: false,
  },
  {
    id: 184,
    img: muftaVk75,
    name: "Муфта двухраструбная ВК ПП 76х87° К,серый RTP",
    brand: "RTP",
    quantity: "70 шт",
    price: 70,
    unit: "шт",
    category: "fitingVK",
    categoryName: "Фитинги ВК",
    allResidual: 0,
    residualValue: "",
    isActive: false,
  },
  {
    id: 185,
    img: muftaVk,
    name: "Муфта двухраструбная ВК ПП 110х87° К,серый RTP",
    brand: "RTP",
    quantity: "70 шт",
    price: 90,
    unit: "шт",
    category: "fitingVK",
    categoryName: "Фитинги ВК",
    allResidual: 0,
    residualValue: "",
    isActive: false,
  },

  // perahod vk
  {
    id: 186,
    img: reduksiya7550,
    name: "Редукция ВК ПП 76\\50 К,серый RTP",
    brand: "RTP",
    quantity: "150 шт",
    price: 50,
    unit: "шт",
    category: "fitingVK",
    categoryName: "Фитинги ВК",
    allResidual: 0,
    residualValue: "",
    isActive: false,
  },
  {
    id: 187,
    img: reduksiya11050,
    name: "Редукция ВК ПП 110\\50 К,серый RTP",
    brand: "RTP",
    quantity: "60 шт",
    price: 66,
    unit: "шт",
    category: "fitingVK",
    categoryName: "Фитинги ВК",
    allResidual: 660,
    residualValue: "",
    isActive: true,
  },
  {
    id: 189,
    img: reduksiya7550,
    name: "Редукция ВК ПП 110\\76 К,серый RTP",
    brand: "RTP",
    quantity: "16 шт",
    price: 90,
    unit: "шт",
    category: "fitingVK",
    categoryName: "Фитинги ВК",
    allResidual: 0,
    residualValue: "",
    isActive: false,
  },
  {
    id: 190,
    img: perehodChu,
    name: "Переход с Чугуна на пластик ВК ПП 100\\124 К,серый RTP",
    brand: "RTP",
    quantity: "36 шт",
    price: 275,
    unit: "шт",
    category: "fitingVK",
    categoryName: "Фитинги ВК",
    allResidual: 74,
    residualValue: "",
    isActive: true,
  },

  // zont vk
  {
    id: 191,
    img: zont110,
    name: "Зонт ВК ПП 110х87 К,серый RTP",
    brand: "RTP",
    quantity: "36 шт",
    price: 110,
    unit: "шт",
    category: "fitingVK",
    categoryName: "Фитинги ВК",
    allResidual: 0,
    residualValue: "",
    isActive: false,
  },
  {
    id: 192,
    img: zont50,
    name: "Зонт ВК ПП 50х87 К,серый RTP",
    brand: "RTP",
    quantity: "60 шт",
    price: 70,
    unit: "шт",
    category: "fitingVK",
    categoryName: "Фитинги ВК",
    allResidual: 0,
    residualValue: "",
    isActive: false,
  },

  // kreztavina
  {
    id: 193,
    img: chetvertak11050lev,
    name: "Крестовина двухплоскостная ВК ПП 110\\110\\50 45° К,серый RTP лев.",
    brand: "RTP",
    quantity: "18 шт",
    price: 230,
    unit: "шт",
    category: "fitingVK",
    categoryName: "Фитинги ВК",
    allResidual: 0,
    residualValue: "",
    isActive: false,
  },
  {
    id: 194,
    img: chetvertak11050prv,
    name: "Крестовина двухплоскостная ВК ПП 110\\110\\50 45° К,серый RTP пра.",
    brand: "RTP",
    quantity: "18 шт",
    price: 230,
    unit: "шт",
    category: "fitingVK",
    categoryName: "Фитинги ВК",
    allResidual: 0,
    residualValue: "",
    isActive: false,
  },
  {
    id: 195,
    img: chetvertak110110,
    name: "Крестовина двухплоскостная ВК ПП 110\\110\\110 45° К,серый RTP",
    brand: "RTP",
    quantity: "18 шт",
    price: 275,
    unit: "шт",
    category: "fitingVK",
    categoryName: "Фитинги ВК",
    allResidual: 0,
    residualValue: "",
    isActive: false,
  },
  {
    id: 196,
    img: kres,
    name: "Крестовина одноплоскостная ВК ПП 110\\110\\100 87° К,серый RTP",
    brand: "RTP",
    quantity: "18 шт",
    price: 240,
    unit: "шт",
    category: "fitingVK",
    categoryName: "Фитинги ВК",
    allResidual: 0,
    residualValue: "",
    isActive: false,
  },
  {
    id: 197,
    img: kres11050,
    name: "Крестовина одноплоскостная ВК ПП 110\\50\\50 87° К,серый RTP",
    brand: "RTP",
    quantity: "42 шт",
    price: 175,
    unit: "шт",
    category: "fitingVK",
    categoryName: "Фитинги ВК",
    allResidual: 0,
    residualValue: "",
    isActive: false,
  },
  {
    id: 198,
    img: kres1105045,
    name: "Крестовина одноплоскостная ВК ПП 110\\50\\50 45° К,серый RTP",
    brand: "RTP",
    quantity: "25 шт",
    price: 175,
    unit: "шт",
    category: "fitingVK",
    categoryName: "Фитинги ВК",
    allResidual: 0,
    residualValue: "",
    isActive: false,
  },

  // obratniy klapn
  {
    id: 199,
    img: obratniyKlapn50,
    name: "Обратный клапан ВК ПП 50ф К,серый RTP",
    brand: "RTP",
    quantity: "1 шт",
    price: 1250,
    unit: "шт",
    category: "fitingVK",
    categoryName: "Фитинги ВК",
    allResidual: 0,
    residualValue: "",
    isActive: false,
  },
  {
    id: 200,
    img: obratniyKlapn110,
    name: "Обратный клапан ВК ПП 110ф К,серый RTP",
    brand: "RTP",
    quantity: "1 шт",
    price: 2000,
    unit: "шт",
    category: "fitingVK",
    categoryName: "Фитинги ВК",
    allResidual: 0,
    residualValue: "",
    isActive: false,
  },

  // klips i homut
  {
    id: 201,
    img: klipsVk,
    name: "(Клипс) Хомут с защелкой ВК ПП 110х87 К,серый RTP",
    brand: "RTP",
    quantity: "300 шт",
    price: 35,
    unit: "шт",
    category: "fitingVK",
    categoryName: "Фитинги ВК",
    allResidual: 0,
    residualValue: "",
    isActive: false,
  },
  {
    id: 202,
    img: klipsVk,
    name: "(Клипс) Хомут с защелкой ВК ПП 76х87 К,серый RTP",
    brand: "RTP",
    quantity: "200 шт",
    price: 30,
    unit: "шт",
    category: "fitingVK",
    categoryName: "Фитинги ВК",
    allResidual: 0,
    residualValue: "",
    isActive: false,
  },
  {
    id: 203,
    img: klipsVk,
    name: "(Клипс) Хомут с защелкой ВК ПП 50х87 К,серый RTP",
    brand: "RTP",
    quantity: "125 шт",
    price: 17,
    unit: "шт",
    category: "fitingVK",
    categoryName: "Фитинги ВК",
    allResidual: 1250,
    residualValue: "",
    isActive: true,
  },
  {
    id: 204,
    img: xomut,
    name: "Хомут в компл (М8) металл 1\\2 (20-25) RTP",
    brand: "RTP",
    quantity: "130 шт",
    price: 25,
    unit: "шт",
    category: "fitingVK",
    categoryName: "Фитинги ВК",
    allResidual: 0,
    residualValue: "",
    isActive: false,
  },
  {
    id: 205,
    img: xomut,
    name: "Хомут в компл (М8) металл 1\\2 (25-29) RTP",
    brand: "RTP",
    quantity: "120 шт",
    price: 28,
    unit: "шт",
    category: "fitingVK",
    categoryName: "Фитинги ВК",
    allResidual: 0,
    residualValue: "",
    isActive: false,
  },
  {
    id: 206,
    img: xomut,
    name: "Хомут в компл (М8) металл 1\\2 (32-34) RTP",
    brand: "RTP",
    quantity: "100 шт",
    price: 32,
    unit: "шт",
    category: "fitingVK",
    categoryName: "Фитинги ВК",
    allResidual: 0,
    residualValue: "",
    isActive: false,
  },
  {
    id: 207,
    img: xomut,
    name: "Хомут в компл (М8) металл1 1\\2 (47-52) RTP",
    brand: "RTP",
    quantity: "75 шт",
    price: 48,
    unit: "шт",
    category: "fitingVK",
    categoryName: "Фитинги ВК",
    allResidual: 0,
    residualValue: "",
    isActive: false,
  },
  {
    id: 208,
    img: xomut,
    name: "Хомут в компл (М8) металл2 1\\2 (73-80) RTP",
    brand: "RTP",
    quantity: "70 шт",
    price: 56,
    unit: "шт",
    category: "fitingVK",
    categoryName: "Фитинги ВК",
    allResidual: 0,
    residualValue: "",
    isActive: false,
  },
  {
    id: 209,
    img: xomut,
    name: "Хомут в компл (М10) металл4 1\\2 (105-115) RTP",
    brand: "RTP",
    quantity: "50 шт",
    price: 60,
    unit: "шт",
    category: "fitingVK",
    categoryName: "Фитинги ВК",
    allResidual: 0,
    residualValue: "",
    isActive: false,
  },
  {
    id: 210,
    img: xomut,
    name: "Хомут в компл (М10) металл6 1\\2 (155-162) RTP",
    brand: "RTP",
    quantity: "30 шт",
    price: 115,
    unit: "шт",
    category: "fitingVK",
    categoryName: "Фитинги ВК",
    allResidual: 0,
    residualValue: "",
    isActive: false,
  },

  // ═══════════════════════════════════════════════════════════
  // 14. fitingNK — Фитинги НК (наружная канализация, рыжий)
  // ═══════════════════════════════════════════════════════════
  {
    id: 211,
    img: otvodNk,
    name: "Отвод НК ПП 110х87 К,рыжый RTP",
    brand: "RTP",
    quantity: "35 шт",
    price: 110,
    unit: "шт",
    category: "fitingNK",
    categoryName: "Фитинги НК",
    allResidual: 350,
    residualValue: "",
    isActive: true,
  },
  {
    id: 212,
    img: otvodNk45,
    name: "Отвод НК ПП 110х45° К,рыжый RTP",
    brand: "RTP",
    quantity: "50 шт",
    price: 105,
    unit: "шт",
    category: "fitingNK",
    categoryName: "Фитинги НК",
    allResidual: 0,
    residualValue: "",
    isActive: false,
  },
  {
    id: 213,
    img: otvodNk,
    name: "Отвод НК ПП 160х87 К,рыжый RTP",
    brand: "RTP",
    quantity: "12 шт",
    price: 440,
    unit: "шт",
    category: "fitingNK",
    categoryName: "Фитинги НК",
    allResidual: 0,
    residualValue: "",
    isActive: false,
  },
  {
    id: 214,
    img: otvodNk45,
    name: "Отвод НК ПП 160х45° К,рыжый RTP",
    brand: "RTP",
    quantity: "16 шт",
    price: 275,
    unit: "шт",
    category: "fitingNK",
    categoryName: "Фитинги НК",
    allResidual: 0,
    residualValue: "",
    isActive: false,
  },
  {
    id: 215,
    img: traynikNk11087,
    name: "Тройник НК ПП 110\\110\\87 К,рыжый RTP",
    brand: "RTP",
    quantity: "32 шт",
    price: 160,
    unit: "шт",
    category: "fitingNK",
    categoryName: "Фитинги НК",
    allResidual: 0,
    residualValue: "",
    isActive: false,
  },
  {
    id: 216,
    img: traynikNk11045,
    name: "Тройник НК ПП 110\\110\\45 К,рыжый RTP",
    brand: "RTP",
    quantity: "24 шт",
    price: 170,
    unit: "шт",
    category: "fitingNK",
    categoryName: "Фитинги НК",
    allResidual: 0,
    residualValue: "",
    isActive: false,
  },
  {
    id: 217,
    img: traynikNk11087,
    name: "Тройник НК ПП 160\\160\\87 К,рыжый RTP",
    brand: "RTP",
    quantity: "8 шт",
    price: 600,
    unit: "шт",
    category: "fitingNK",
    categoryName: "Фитинги НК",
    allResidual: 0,
    residualValue: "",
    isActive: false,
  },
  {
    id: 218,
    img: traynikNk11045,
    name: "Тройник НК ПП 160\\160\\45 К,рыжый RTP",
    brand: "RTP",
    quantity: "6 шт",
    price: 715,
    unit: "шт",
    category: "fitingNK",
    categoryName: "Фитинги НК",
    allResidual: 0,
    residualValue: "",
    isActive: false,
  },
  {
    id: 219,
    img: traynikNk16011087,
    name: "Тройник НК ПП 160\\110х87 К,рыжый RTP",
    brand: "RTP",
    quantity: "10 шт",
    price: 495,
    unit: "шт",
    category: "fitingNK",
    categoryName: "Фитинги НК",
    allResidual: 0,
    residualValue: "",
    isActive: false,
  },
  {
    id: 220,
    img: reviziyaNk,
    name: "Ревизия с крышкой НК ПП 110х87° К,рыжый RTP",
    brand: "RTP",
    quantity: "36 шт",
    price: 180,
    unit: "шт",
    category: "fitingNK",
    categoryName: "Фитинги НК",
    allResidual: 0,
    residualValue: "",
    isActive: false,
  },
  {
    id: 221,
    img: reviziyaNk160110,
    name: "Ревизия с крышкой НК ПП 160\\110х87° К,рыжый RTP",
    brand: "RTP",
    quantity: "10 шт",
    price: 715,
    unit: "шт",
    category: "fitingNK",
    categoryName: "Фитинги НК",
    allResidual: 0,
    residualValue: "",
    isActive: false,
  },
  {
    id: 222,
    img: reviziyaNk,
    name: "Ревизия с крышкой НК ПП 160х87° К,рыжый RTP",
    brand: "RTP",
    quantity: "9 шт",
    price: 715,
    unit: "шт",
    category: "fitingNK",
    categoryName: "Фитинги НК",
    allResidual: 0,
    residualValue: "",
    isActive: false,
  },
  {
    id: 223,
    img: zagulushkaNk,
    name: "Заглушка НК ПП 110х87° К,рыжый RTP",
    brand: "RTP",
    quantity: "40 шт",
    price: 35,
    unit: "шт",
    category: "fitingNK",
    categoryName: "Фитинги НК",
    allResidual: 0,
    residualValue: "",
    isActive: false,
  },
  {
    id: 224,
    img: zagulushkaNk,
    name: "Заглушка НК ПП 160х87° К,рыжый RTP",
    brand: "RTP",
    quantity: "45 шт",
    price: 135,
    unit: "шт",
    category: "fitingNK",
    categoryName: "Фитинги НК",
    allResidual: 0,
    residualValue: "",
    isActive: false,
  },
  {
    id: 225,
    img: muftaNk,
    name: "Муфта двухраструбная НК ПП 110х87° К,рыжый RTP",
    brand: "RTP",
    quantity: "65 шт",
    price: 100,
    unit: "шт",
    category: "fitingNK",
    categoryName: "Фитинги НК",
    allResidual: 0,
    residualValue: "",
    isActive: false,
  },
  {
    id: 226,
    img: muftaNk,
    name: "Муфта двухраструбная НК ПП 160х87° К,рыжый RTP",
    brand: "RTP",
    quantity: "20 шт",
    price: 385,
    unit: "шт",
    category: "fitingNK",
    categoryName: "Фитинги НК",
    allResidual: 0,
    residualValue: "",
    isActive: false,
  },
  {
    id: 227,
    img: reduksiyaNk160110,
    name: "Редукция НК ПП 160\\110 К,серый RTP",
    brand: "RTP",
    quantity: "42 шт",
    price: 255,
    unit: "шт",
    category: "fitingNK",
    categoryName: "Фитинги НК",
    allResidual: 0,
    residualValue: "",
    isActive: false,
  },
  {
    id: 228,
    img: obratniyKlapnNk110,
    name: "Обратный клапан НК ПП 110ф К,рыжый RTP",
    brand: "RTP",
    quantity: "1 шт",
    price: 2300,
    unit: "шт",
    category: "fitingNK",
    categoryName: "Фитинги НК",
    allResidual: 0,
    residualValue: "",
    isActive: false,
  },
  {
    id: 229,
    img: obratniyKlapn160,
    name: "Обратный клапан НК ПП 160ф К,рыжый RTP",
    brand: "RTP",
    quantity: "1 шт",
    price: 4000,
    unit: "шт",
    category: "fitingNK",
    categoryName: "Фитинги НК",
    allResidual: 0,
    residualValue: "",
    isActive: false,
  },
];



///  test yakuni 




// RTP praduct list export
export const allDataRTPAdir = dataRTPAdir
.filter((itim)=>itim.isActive)
.map((itim)=>({
  ...itim,
  residualValue:itim.price * itim.allResidual
}));

// products count
export const productsCount = allDataRTPAdir.length;

// all products  residual valyue
export const totalResidualValue = allDataRTPAdir.reduce(
  (sum, item) => sum + item.residualValue,
  0
);