import trubaRtp from "@/assets/productImgs/rtp/trubaPPR.webp";



export const dataRTPAdir = [
  // ==================== ТРУБА PPR (PN 20) ====================
  {
    id: 1,
    img: trubaRtp,
    name: "Труба PPR 20х3,4 (PN 20) 4м белый RTP",
    brand: "RTP",
    quantity: "100/4м",
    price: 42,
    allResidual: 29000,
    residualValue: "",
    unit: "м",
    isActive: true,
    category: "trubaPPR",
  },
  {
    id: 2,
    img: trubaRtp,
    name: "Труба PPR 25x4,2 (PN 20) 4м белый RTP",
    brand: "RTP",
    quantity: "100/4м",
    price: 69,
    allResidual: 5800,
    residualValue: "",
    unit: "м",
    isActive: true,
    category: "trubaPPR",
  },
  {
    id: 3,
    img: trubaRtp,
    name: "Труба PPR 32x5,4 (PN 20) 4м белый RTP",
    brand: "RTP",
    quantity: "100/4м",
    price: 115,
    allResidual: 0,
    residualValue: "",
    unit: "м",
    isActive: false,
    category: "trubaPPR",
  },
  {
    id: 4,
    img: trubaRtp,
    name: "Труба PPR 40х6,7 (PN 20) 4м белый RTP",
    brand: "RTP",
    quantity: "100/4м",
    price: 175,
    allResidual: 0,
    residualValue: "",
    unit: "м",
    isActive: false,
    category: "trubaPPR",
  },
  {
    id: 5,
    img: trubaRtp,
    name: "Труба PPR 50x8,3 (PN 20) 4м белый RTP",
    brand: "RTP",
    quantity: "100/4м",
    price: 280,
    allResidual: 0,
    residualValue: "",
    unit: "м",
    isActive: false,
    category: "trubaPPR",
  },
  {
    id: 6,
    img: trubaRtp,
    name: "Труба PPR GF\\PPR 20x3,4 (PN 25) 4м белый RTP",
    brand: "RTP",
    quantity: "100/4м",
    price: 51,
    allResidual: 16000,
    residualValue: "",
    unit: "м",
    isActive: true,
    category: "trubaPPR",
  },
  {
    id: 7,
    img: trubaRtp,
    name: "Труба PPR GF\\PPR 25x4,2 (PN 25) 4м белый RTP",
    brand: "RTP",
    quantity: "100/4м",
    price: 11400,
    allResidual: 0,
    residualValue: "",
    unit: "м",
    isActive: true,
    category: "trubaPPR",
  },
  {
    id: 8,
    img: trubaRtp,
    name: "Труба PPR GF\\PPR 32x5,4 (PN 25) 4м белый RTP",
    brand: "RTP",
    quantity: "60/4м",
    price: 127,
    allResidual: 14520,
    residualValue: "",
    unit: "м",
    isActive: true,
    category: "trubaPPR",
  },
  {
    id: 9,
    img: trubaRtp,
    name: "Труба PPR GF\\PPR 40x6,7 (PN 25) 4м белый RTP",
    brand: "RTP",
    quantity: "100/4м",
    price: 215,
    allResidual: 0,
    residualValue: "",
    unit: "м",
    isActive: false,
    category: "trubaPPR",
  },
  {
    id: 10,
    img: trubaRtp,
    name: "Труба PPR GF\\PPR 50x8,3 (PN 25) 4м белый RTP",
    brand: "RTP",
    quantity: "100/4м",
    price: 300,
    allResidual: 0,
    residualValue: "",
    unit: "м",
    isActive: false,
    category: "trubaPPR",
  },

  // ==================== МУФТА СОЕДИНИТЕЛЬНАЯ ====================
  {
    id: 11,
    img: trubaRtp,
    name: "Муфта соединительная PPR 20ф PN25 белый RTP",
    brand: "RTP",
    quantity: "500/50 шт",
    price: 5,
    allResidual: 37500,
    residualValue: "",
    unit: "шт",
    isActive: true,
    category: "fitingPPR",
  },
  {
    id: 12,
    img: trubaRtp,
    name: "Муфта соединительная PPR 25ф PN25 белый RTP",
    brand: "RTP",
    quantity: "400 шт",
    price: 7,
    allResidual: 24000,
    residualValue: "",
    unit: "шт",
    isActive: true,
    category: "fitingPPR",
  },
  {
    id: 13,
    img: trubaRtp,
    name: "Муфта соединительная PPR 32ф PN25 белый RTP",
    brand: "RTP",
    quantity: "245 шт",
    price: 14,
    allResidual: 12740,
    residualValue: "",
    unit: "шт",
    isActive: true,
    category: "fitingPPR",
  },
  {
    id: 14,
    img: trubaRtp,
    name: "Муфта соединительная PPR 40ф PN25 белый RTP",
    brand: "RTP",
    quantity: "140 шт",
    price: 25,
    allResidual: 1400,
    residualValue: "",
    unit: "шт",
    isActive: true,
    category: "fitingPPR",
  },
  {
    id: 15,
    img: trubaRtp,
    name: "Муфта соединительная PPR 50ф PN25 белый RTP",
    brand: "RTP",
    quantity: "100 шт",
    price: 50,
    allResidual: 200,
    residualValue: "",
    unit: "шт",
    isActive: true,
    category: "fitingPPR",
  },
  {
    id: 16,
    img: trubaRtp,
    name: "Муфта соединительная PPR 63ф PN25 белый RTP",
    brand: "RTP",
    quantity: "24 шт",
    price: 80,
    allResidual: 168,
    residualValue: "",
    unit: "шт",
    isActive: true,
    category: "fitingPPR",
  },

  // ==================== УГОЛЬНИК 45° ====================
  {
    id: 17,
    img: trubaRtp,
    name: "Угольник PPR 45° 20ф PN25 белый RTP",
    brand: "RTP",
    quantity: "1 шт",
    price: 5,
    allResidual: 0,
    residualValue: "",
    unit: "шт",
    isActive: false,
    category: "fitingPPR",
  },
  {
    id: 18,
    img: trubaRtp,
    name: "Угольник PPR 45° 25ф PN25 белый RTP",
    brand: "RTP",
    quantity: "1 шт",
    price: 8,
    allResidual: 0,
    residualValue: "",
    unit: "шт",
    isActive: false,
    category: "fitingPPR",
  },
  {
    id: 19,
    img: trubaRtp,
    name: "Угольник PPR 45° 32ф PN25 белый RTP",
    brand: "RTP",
    quantity: "1 шт",
    price: 17,
    allResidual: 0,
    residualValue: "",
    unit: "шт",
    isActive: false,
    category: "fitingPPR",
  },
  {
    id: 20,
    img: trubaRtp,
    name: "Угольник PPR 45° 40ф PN25 белый RTP",
    brand: "RTP",
    quantity: "1 шт",
    price: 35,
    allResidual: 0,
    residualValue: "",
    unit: "шт",
    isActive: false,
    category: "fitingPPR",
  },
  {
    id: 21,
    img: trubaRtp,
    name: "Угольник PPR 45° 50ф PN25 белый RTP",
    brand: "RTP",
    quantity: "1 шт",
    price: 50,
    allResidual: 0,
    residualValue: "",
    unit: "шт",
    isActive: false,
    category: "fitingPPR",
  },
  {
    id: 22,
    img: trubaRtp,
    name: "Угольник PPR 45° 63ф PN25 белый RTP",
    brand: "RTP",
    quantity: "1 шт",
    price: 80,
    allResidual: 0,
    residualValue: "",
    unit: "шт",
    isActive: false,
    category: "fitingPPR",
  },

  // ==================== УГОЛЬНИК 90° ====================
  {
    id: 23,
    img: trubaRtp,
    name: "Угольник PPR 90° 20ф PN25 белый RTP",
    brand: "RTP",
    quantity: "400 шт",
    price: 6,
    allResidual: 80000,
    residualValue: "",
    unit: "шт",
    isActive: true,
    category: "fitingPPR",
  },
  {
    id: 24,
    img: trubaRtp,
    name: "Угольник PPR 90° 25ф PN25 белый RTP",
    brand: "RTP",
    quantity: "240 шт",
    price: 9,
    allResidual: 34560,
    residualValue: "",
    unit: "шт",
    isActive: true,
    category: "fitingPPR",
  },
  {
    id: 25,
    img: trubaRtp,
    name: "Угольник PPR 90° 32ф PN25 белый RTP",
    brand: "RTP",
    quantity: "140 шт",
    price: 18,
    allResidual: 28280,
    residualValue: "",
    unit: "шт",
    isActive: true,
    category: "fitingPPR",
  },
  {
    id: 26,
    img: trubaRtp,
    name: "Угольник PPR 90° 40ф PN25 белый RTP",
    brand: "RTP",
    quantity: "1 шт",
    price: 35,
    allResidual: 0,
    residualValue: "",
    unit: "шт",
    isActive: false,
    category: "fitingPPR",
  },
  {
    id: 27,
    img: trubaRtp,
    name: "Угольник PPR 90° 50ф PN25 белый RTP",
    brand: "RTP",
    quantity: "1 шт",
    price: 60,
    allResidual: 0,
    residualValue: "",
    unit: "шт",
    isActive: false,
    category: "fitingPPR",
  },
  {
    id: 28,
    img: trubaRtp,
    name: "Угольник PPR 90° 63ф PN25 белый RTP",
    brand: "RTP",
    quantity: "1 шт",
    price: 90,
    allResidual: 0,
    residualValue: "",
    unit: "шт",
    isActive: false,
    category: "fitingPPR",
  },

  // ==================== ТРОЙНИК PPR ====================
  {
    id: 29,
    img: trubaRtp,
    name: "Тройник PPR 20ф PN25 белый RTP",
    brand: "RTP",
    quantity: "280 шт",
    price: 7,
    allResidual: 38000,
    residualValue: "",
    unit: "шт",
    isActive: true,
    category: "fitingPPR",
  },
  {
    id: 30,
    img: trubaRtp,
    name: "Тройник PPR 25ф PN25 белый RTP",
    brand: "RTP",
    quantity: "175 шт",
    price: 12,
    allResidual: 8650,
    residualValue: "",
    unit: "шт",
    isActive: true,
    category: "fitingPPR",
  },
  {
    id: 31,
    img: trubaRtp,
    name: "Тройник PPR 32ф PN25 белый RTP",
    brand: "RTP",
    quantity: "1 шт",
    price: 20,
    allResidual: 0,
    residualValue: "",
    unit: "шт",
    isActive: false,
    category: "fitingPPR",
  },
  {
    id: 32,
    img: trubaRtp,
    name: "Тройник PPR 40ф PN25 белый RTP",
    brand: "RTP",
    quantity: "1 шт",
    price: 35,
    allResidual: 0,
    residualValue: "",
    unit: "шт",
    isActive: false,
    category: "fitingPPR",
  },
  {
    id: 33,
    img: trubaRtp,
    name: "Тройник PPR 50ф PN25 белый RTP",
    brand: "RTP",
    quantity: "1 шт",
    price: 70,
    allResidual: 0,
    residualValue: "",
    unit: "шт",
    isActive: false,
    category: "fitingPPR",
  },
  {
    id: 34,
    img: trubaRtp,
    name: "Тройник PPR 63ф PN25 белый RTP",
    brand: "RTP",
    quantity: "1 шт",
    price: 100,
    allResidual: 0,
    residualValue: "",
    unit: "шт",
    isActive: false,
    category: "fitingPPR",
  },

  // ==================== ТРОЙНИК ПЕРЕХОДНОЙ ====================
  {
    id: 35,
    img: trubaRtp,
    name: "Тройник переходной PPR 25\\20\\25ф PN25 белый RTP",
    brand: "RTP",
    quantity: "1 шт",
    price: 10,
    allResidual: 0,
    residualValue: "",
    unit: "шт",
    isActive: false,
    category: "fitingPPR",
  },
  {
    id: 36,
    img: trubaRtp,
    name: "Тройник переходной PPR 32\\20\\32ф PN25 белый RTP",
    brand: "RTP",
    quantity: "1 шт",
    price: 18,
    allResidual: 0,
    residualValue: "",
    unit: "шт",
    isActive: false,
    category: "fitingPPR",
  },
  {
    id: 37,
    img: trubaRtp,
    name: "Тройник переходной PPR 32\\25\\32ф PN25 белый RTP",
    brand: "RTP",
    quantity: "1 шт",
    price: 18,
    allResidual: 0,
    residualValue: "",
    unit: "шт",
    isActive: false,
    category: "fitingPPR",
  },
  {
    id: 38,
    img: trubaRtp,
    name: "Тройник переходной PPR 40\\20\\40ф PN25 белый RTP",
    brand: "RTP",
    quantity: "1 шт",
    price: 30,
    allResidual: 0,
    residualValue: "",
    unit: "шт",
    isActive: false,
    category: "fitingPPR",
  },
  {
    id: 39,
    img: trubaRtp,
    name: "Тройник переходной PPR 40\\25\\40ф PN25 белый RTP",
    brand: "RTP",
    quantity: "1 шт",
    price: 30,
    allResidual: 0,
    residualValue: "",
    unit: "шт",
    isActive: false,
    category: "fitingPPR",
  },
  {
    id: 40,
    img: trubaRtp,
    name: "Тройник переходной PPR 40\\32\\40ф PN25 белый RTP",
    brand: "RTP",
    quantity: "1 шт",
    price: 30,
    allResidual: 0,
    residualValue: "",
    unit: "шт",
    isActive: false,
    category: "fitingPPR",
  },

  // ==================== УГОЛЬНИК С КРЕПЛЕНИЕМ ====================
  {
    id: 41,
    img: trubaRtp,
    name: "Угольник с креплением PPR В\\Р 20х1\\2 PN25 белый RTP",
    brand: "RTP",
    quantity: "1 шт",
    price: 65,
    allResidual: 0,
    residualValue: "",
    unit: "шт",
    isActive: false,
    category: "fitingPPR",
  },
  {
    id: 42,
    img: trubaRtp,
    name: "Угольник с креплением PPR Н\\Р 20х1\\2 PN25 белый RTP",
    brand: "RTP",
    quantity: "75/25 шт",
    price: 70,
    allResidual: 4055,
    residualValue: "",
    unit: "шт",
    isActive: true,
    category: "fitingPPR",
  },
  {
    id: 43,
    img: trubaRtp,
    name: "Угольник с креплением PPR В\\Р 25х1\\2 PN25 белый RTP",
    brand: "RTP",
    quantity: "1 шт",
    price: 75,
    allResidual: 0,
    residualValue: "",
    unit: "шт",
    isActive: false,
    category: "fitingPPR",
  },
  {
    id: 44,
    img: trubaRtp,
    name: "Угольник с креплением PPR Н\\Р 25х1\\2 PN25 белый RTP",
    brand: "RTP",
    quantity: "1 шт",
    price: 80,
    allResidual: 0,
    residualValue: "",
    unit: "шт",
    isActive: false,
    category: "fitingPPR",
  },

  // ==================== УГОЛ КОМ П/СМЕС ====================
  {
    id: 45,
    img: trubaRtp,
    name: "Угол ком п\\смес PPR В\\Р 20х1\\2 PN25 белый RTP",
    brand: "RTP",
    quantity: "1 шт",
    price: 110,
    allResidual: 0,
    residualValue: "",
    unit: "шт",
    isActive: false,
    category: "fitingPPR",
  },
  {
    id: 46,
    img: trubaRtp,
    name: "Угол ком п\\смес PPR Н\\Р 20х3\\4 PN25 белый RTP",
    brand: "RTP",
    quantity: "1 шт",
    price: 200,
    allResidual: 0,
    residualValue: "",
    unit: "шт",
    isActive: false,
    category: "fitingPPR",
  },
  {
    id: 47,
    img: trubaRtp,
    name: "Угол ком п\\смес PPR Н\\Р 20х1\\2 PN25 белый RTP",
    brand: "RTP",
    quantity: "1 шт",
    price: 110,
    allResidual: 0,
    residualValue: "",
    unit: "шт",
    isActive: false,
    category: "fitingPPR",
  },
  {
    id: 48,
    img: trubaRtp,
    name: "Угол ком п\\смес PPR Н\\Р 25х1\\2 PN25 белый RTP",
    brand: "RTP",
    quantity: "1 шт",
    price: 115,
    allResidual: 0,
    residualValue: "",
    unit: "шт",
    isActive: false,
    category: "fitingPPR",
  },

  // ==================== ОПОРА С ЗАЩЕЛКОЙ ====================
  {
    id: 49,
    img: trubaRtp,
    name: "Опора с защелкой PPR 20ф PN25 белый RTP",
    brand: "RTP",
    quantity: "360 шт",
    price: 3,
    allResidual: 11360,
    residualValue: "",
    unit: "шт",
    isActive: true,
    category: "fitingPPR",
  },
  {
    id: 50,
    img: trubaRtp,
    name: "Опора с защелкой PPR 25ф PN25 белый RTP",
    brand: "RTP",
    quantity: "1 шт",
    price: 4,
    allResidual: 0,
    residualValue: "",
    unit: "шт",
    isActive: false,
    category: "fitingPPR",
  },
  {
    id: 51,
    img: trubaRtp,
    name: "Опора с защелкой PPR 25ф PN25 серый RTP",
    brand: "RTP",
    quantity: "210 шт",
    price: 6,
    allResidual: 11470,
    residualValue: "",
    unit: "шт",
    isActive: true,
    category: "fitingPPR",
  },
  {
    id: 52,
    img: trubaRtp,
    name: "Опора с защелкой PPR 32ф PN25 белый RTP",
    brand: "RTP",
    quantity: "1 шт",
    price: 8,
    allResidual: 0,
    residualValue: "",
    unit: "шт",
    isActive: false,
    category: "fitingPPR",
  },
  {
    id: 53,
    img: trubaRtp,
    name: "Опора с защелкой PPR 40ф PN25 белый RTP",
    brand: "RTP",
    quantity: "1 шт",
    price: 10,
    allResidual: 0,
    residualValue: "",
    unit: "шт",
    isActive: false,
    category: "fitingPPR",
  },

  // ==================== ОБВОДНОЕ КОЛЕНО ====================
  {
    id: 54,
    img: trubaRtp,
    name: "Обводное колено с муфтой PPR 20ф PN25 белый RTP",
    brand: "RTP",
    quantity: "100 шт",
    price: 14,
    allResidual: 8000,
    residualValue: "",
    unit: "шт",
    isActive: true,
    category: "fitingPPR",
  },
  {
    id: 55,
    img: trubaRtp,
    name: "Обводное колено с муфтой PPR 25ф PN25 белый RTP",
    brand: "RTP",
    quantity: "1 шт",
    price: 20,
    allResidual: 0,
    residualValue: "",
    unit: "шт",
    isActive: false,
    category: "fitingPPR",
  },
  {
    id: 56,
    img: trubaRtp,
    name: "Обводное колено с муфтой PPR 32ф PN25 белый RTP",
    brand: "RTP",
    quantity: "1 шт",
    price: 40,
    allResidual: 0,
    residualValue: "",
    unit: "шт",
    isActive: false,
    category: "fitingPPR",
  },

  // ==================== ЗАГЛУШКА PPR ====================
  {
    id: 57,
    img: trubaRtp,
    name: "Заглушка PPR 20ф PN25 белый RTP",
    brand: "RTP",
    quantity: "390 шт",
    price: 5,
    allResidual: 4290,
    residualValue: "",
    unit: "шт",
    isActive: true,
    category: "fitingPPR",
  },
  {
    id: 58,
    img: trubaRtp,
    name: "Заглушка PPR 25ф PN25 белый RTP",
    brand: "RTP",
    quantity: "240 шт",
    price: 7,
    allResidual: 4080,
    residualValue: "",
    unit: "шт",
    isActive: true,
    category: "fitingPPR",
  },
  {
    id: 59,
    img: trubaRtp,
    name: "Заглушка PPR 32ф PN25 белый RTP",
    brand: "RTP",
    quantity: "1 шт",
    price: 10,
    allResidual: 0,
    residualValue: "",
    unit: "шт",
    isActive: false,
    category: "fitingPPR",
  },
  {
    id: 60,
    img: trubaRtp,
    name: "Заглушка PPR 40ф PN25 белый RTP",
    brand: "RTP",
    quantity: "1 шт",
    price: 20,
    allResidual: 0,
    residualValue: "",
    unit: "шт",
    isActive: false,
    category: "fitingPPR",
  },

  // ==================== КРАН ШАРОВОЙ ====================
  {
    id: 61,
    img: trubaRtp,
    name: "Кран шаровой СТпрох PPR 20ф PN25 белый RTP",
    brand: "RTP",
    quantity: "60 шт",
    price: 125,
    allResidual: 3420,
    residualValue: "",
    unit: "шт",
    isActive: true,
    category: "kran",
  },
  {
    id: 62,
    img: trubaRtp,
    name: "Кран шаровой ПЛпрох PPR 20ф PN25 белый RTP",
    brand: "RTP",
    quantity: "1 шт",
    price: 140,
    allResidual: 0,
    residualValue: "",
    unit: "шт",
    isActive: false,
    category: "kran",
  },
  {
    id: 63,
    img: trubaRtp,
    name: "Кран шаровой СТпрох PPR 25ф PN25 белый RTP",
    brand: "RTP",
    quantity: "40 шт",
    price: 180,
    allResidual: 4440,
    residualValue: "",
    unit: "шт",
    isActive: true,
    category: "kran",
  },
  {
    id: 64,
    img: trubaRtp,
    name: "Кран шаровой ПЛпрох PPR 25ф PN25 белый RTP",
    brand: "RTP",
    quantity: "1 шт",
    price: 230,
    allResidual: 0,
    residualValue: "",
    unit: "шт",
    isActive: false,
    category: "kran",
  },
  {
    id: 65,
    img: trubaRtp,
    name: "Кран шаровой СТпрох PPR 32ф PN25 белый RTP",
    brand: "RTP",
    quantity: "1 шт",
    price: 280,
    allResidual: 0,
    residualValue: "",
    unit: "шт",
    isActive: false,
    category: "kran",
  },
  {
    id: 66,
    img: trubaRtp,
    name: "Кран шаровой ПЛпрох PPR 32ф PN25 белый RTP",
    brand: "RTP",
    quantity: "1 шт",
    price: 330,
    allResidual: 0,
    residualValue: "",
    unit: "шт",
    isActive: false,
    category: "kran",
  },
  {
    id: 67,
    img: trubaRtp,
    name: "Кран шаровой СТпрох PPR 40ф PN25 белый RTP",
    brand: "RTP",
    quantity: "20 шт",
    price: 705,
    allResidual: 80,
    residualValue: "",
    unit: "шт",
    isActive: true,
    category: "kran",
  },
  {
    id: 68,
    img: trubaRtp,
    name: "Кран шаровой СТпрох PPR 50ф PN25 белый RTP",
    brand: "RTP",
    quantity: "1 шт",
    price: 800,
    allResidual: 0,
    residualValue: "",
    unit: "шт",
    isActive: false,
    category: "kran",
  },
  {
    id: 69,
    img: trubaRtp,
    name: "Кран шаровой СТпрох PPR 63ф PN25 белый RTP",
    brand: "RTP",
    quantity: "4 шт",
    price: 1300,
    allResidual: 16,
    residualValue: "",
    unit: "шт",
    isActive: true,
    category: "kran",
  },
  {
    id: 70,
    img: trubaRtp,
    name: "Кран шаровой для радиатора PPR прямой 20х1\\2ф PN25 белый RTP",
    brand: "RTP",
    quantity: "1 шт",
    price: 300,
    allResidual: 0,
    residualValue: "",
    unit: "шт",
    isActive: false,
    category: "kran",
  },
  {
    id: 71,
    img: trubaRtp,
    name: "Кран шаровой для радиатора PPR угловой 20х1\\2ф PN25 белый RTP",
    brand: "RTP",
    quantity: "1 шт",
    price: 300,
    allResidual: 0,
    residualValue: "",
    unit: "шт",
    isActive: false,
    category: "kran",
  },
  {
    id: 72,
    img: trubaRtp,
    name: "Кран шаровой для радиатора PPR прямой 25х3\\4ф PN25 белый RTP",
    brand: "RTP",
    quantity: "1 шт",
    price: 350,
    allResidual: 0,
    residualValue: "",
    unit: "шт",
    isActive: false,
    category: "kran",
  },
  {
    id: 73,
    img: trubaRtp,
    name: "Кран шаровой для радиатора PPR угловой 25х3\\4ф PN25 белый RTP",
    brand: "RTP",
    quantity: "35 шт",
    price: 350,
    allResidual: 2345,
    residualValue: "",
    unit: "шт",
    isActive: true,
    category: "kran",
  },

  // ==================== ВЕНТИЛЬ ====================
  {
    id: 74,
    img: trubaRtp,
    name: "Вентиль 90° в сборе ВН\\ВН PPR 20ф PN25 белый RTP",
    brand: "RTP",
    quantity: "40 шт",
    price: 350,
    allResidual: 1400,
    residualValue: "",
    unit: "шт",
    isActive: true,
    category: "kran",
  },
  {
    id: 75,
    img: trubaRtp,
    name: "Вентиль 90° в сборе ВН\\ВН PPR 25ф PN25 белый RTP",
    brand: "RTP",
    quantity: "25 шт",
    price: 380,
    allResidual: 400,
    residualValue: "",
    unit: "шт",
    isActive: true,
    category: "kran",
  },
  {
    id: 76,
    img: trubaRtp,
    name: "Вентиль 90° в сборе ВН\\ВН PPR 32ф PN25 белый RTP",
    brand: "RTP",
    quantity: "15 шт",
    price: 410,
    allResidual: 146,
    residualValue: "",
    unit: "шт",
    isActive: true,
    category: "kran",
  },
  {
    id: 77,
    img: trubaRtp,
    name: "Вентиль 90° в сборе ВН\\ВН PPR 40ф PN25 белый RTP",
    brand: "RTP",
    quantity: "1 шт",
    price: 0,
    allResidual: 0,
    residualValue: "",
    unit: "шт",
    isActive: false,
    category: "kran",
  },

  // ==================== МУФТА КОМБИНИРОВАННАЯ ====================
  {
    id: 78,
    img: trubaRtp,
    name: "Муфта комбинированная с В\\Р PPR 20х1\\2ф PN25 белый RTP",
    brand: "RTP",
    quantity: "150 шт",
    price: 55,
    allResidual: 5,
    residualValue: "",
    unit: "шт",
    isActive: true,
    category: "fitingPPR",
  },
  {
    id: 79,
    img: trubaRtp,
    name: "Муфта комбинированная с В\\Р PPR 20х3\\4ф PN25 белый RTP",
    brand: "RTP",
    quantity: "1 шт",
    price: 65,
    allResidual: 0,
    residualValue: "",
    unit: "шт",
    isActive: false,
    category: "fitingPPR",
  },
  {
    id: 80,
    img: trubaRtp,
    name: "Муфта комбинированная с Н\\Р PPR 20х1\\2ф PN25 белый RTP",
    brand: "RTP",
    quantity: "150 шт",
    price: 62,
    allResidual: 10150,
    residualValue: "",
    unit: "шт",
    isActive: true,
    category: "fitingPPR",
  },
  {
    id: 81,
    img: trubaRtp,
    name: "Муфта комбинированная с Н\\Р PPR 20х3\\4ф PN25 белый RTP",
    brand: "RTP",
    quantity: "1 шт",
    price: 100,
    allResidual: 0,
    residualValue: "",
    unit: "шт",
    isActive: false,
    category: "fitingPPR",
  },
  {
    id: 82,
    img: trubaRtp,
    name: "Муфта комбинированная с В\\Р PPR 25х3\\4ф PN25 белый RTP",
    brand: "RTP",
    quantity: "1 шт",
    price: 65,
    allResidual: 0,
    residualValue: "",
    unit: "шт",
    isActive: false,
    category: "fitingPPR",
  },
  {
    id: 83,
    img: trubaRtp,
    name: "Муфта комбинированная с Н\\Р PPR 25х3\\4ф PN25 белый RTP",
    brand: "RTP",
    quantity: "1 шт",
    price: 75,
    allResidual: 0,
    residualValue: "",
    unit: "шт",
    isActive: false,
    category: "fitingPPR",
  },
  {
    id: 84,
    img: trubaRtp,
    name: "Муфта комбинированная с В\\Р PPR 32х1ф PN25 белый RTP",
    brand: "RTP",
    quantity: "1 шт",
    price: 115,
    allResidual: 0,
    residualValue: "",
    unit: "шт",
    isActive: false,
    category: "fitingPPR",
  },
  {
    id: 85,
    img: trubaRtp,
    name: "Муфта комбинированная с Н\\Р PPR 32х1ф PN25 белый RTP",
    brand: "RTP",
    quantity: "1 шт",
    price: 140,
    allResidual: 0,
    residualValue: "",
    unit: "шт",
    isActive: false,
    category: "fitingPPR",
  },
  {
    id: 86,
    img: trubaRtp,
    name: "Муфта комбинированная с В\\Р PPR 40х1 1\\4ф PN25 белый RTP",
    brand: "RTP",
    quantity: "1 шт",
    price: 341,
    allResidual: 0,
    residualValue: "",
    unit: "шт",
    isActive: false,
    category: "fitingPPR",
  },
  {
    id: 87,
    img: trubaRtp,
    name: "Муфта комбинированная с Н\\Р PPR 40х1 1\\4ф PN25 белый RTP",
    brand: "RTP",
    quantity: "1 шт",
    price: 456,
    allResidual: 0,
    residualValue: "",
    unit: "шт",
    isActive: false,
    category: "fitingPPR",
  },
  {
    id: 88,
    img: trubaRtp,
    name: "Муфта комбинированная с В\\Р PPR 50х1 1\\2ф PN25 белый RTP",
    brand: "RTP",
    quantity: "1 шт",
    price: 300,
    allResidual: 0,
    residualValue: "",
    unit: "шт",
    isActive: false,
    category: "fitingPPR",
  },
  {
    id: 89,
    img: trubaRtp,
    name: "Муфта комбинированная с Н\\Р PPR 50х1 1\\2ф PN25 белый RTP",
    brand: "RTP",
    quantity: "1 шт",
    price: 530,
    allResidual: 0,
    residualValue: "",
    unit: "шт",
    isActive: false,
    category: "fitingPPR",
  },

  // ==================== МУФТА КОМБИНИРОВАННАЯ РАЗЪЕМНАЯ (АМЕРИКАНКА) ====================
  {
    id: 90,
    img: trubaRtp,
    name: "Муфта комбинированная разъемная (американка) с В\\Р PPR 20х1\\2 PN25 белый RTP",
    brand: "RTP",
    quantity: "1 шт",
    price: 135,
    allResidual: 0,
    residualValue: "",
    unit: "шт",
    isActive: false,
    category: "fitingPPR",
  },
  {
    id: 91,
    img: trubaRtp,
    name: "Муфта комбинированная разъемная (американка) с Н\\Р PPR 20х1\\2 PN25 белый RTP",
    brand: "RTP",
    quantity: "1 шт",
    price: 140,
    allResidual: 0,
    residualValue: "",
    unit: "шт",
    isActive: false,
    category: "fitingPPR",
  },
  {
    id: 92,
    img: trubaRtp,
    name: "Муфта комбинированная разъемная (американка) с В\\Р PPR 20х3\\4 PN25 белый RTP",
    brand: "RTP",
    quantity: "1 шт",
    price: 130,
    allResidual: 0,
    residualValue: "",
    unit: "шт",
    isActive: false,
    category: "fitingPPR",
  },
  {
    id: 93,
    img: trubaRtp,
    name: "Муфта комбинированная разъемная (американка) с Н\\Р PPR 20х3\\4 PN25 белый RTP",
    brand: "RTP",
    quantity: "1 шт",
    price: 140,
    allResidual: 0,
    residualValue: "",
    unit: "шт",
    isActive: false,
    category: "fitingPPR",
  },
  {
    id: 94,
    img: trubaRtp,
    name: "Муфта комбинированная разъемная (американка) с Н\\Р PPR 20х1 PN25 белый RTP",
    brand: "RTP",
    quantity: "100 шт",
    price: 245,
    allResidual: 500,
    residualValue: "",
    unit: "шт",
    isActive: true,
    category: "fitingPPR",
  },
  {
    id: 95,
    img: trubaRtp,
    name: "Муфта комбинированная разъемная (американка) с В\\Р PPR 25х3\\4 PN25 белый RTP",
    brand: "RTP",
    quantity: "1 шт",
    price: 165,
    allResidual: 0,
    residualValue: "",
    unit: "шт",
    isActive: false,
    category: "fitingPPR",
  },
  {
    id: 96,
    img: trubaRtp,
    name: "Муфта комбинированная разъемная (американка) с Н\\Р PPR 25х3\\4 PN25 белый RTP",
    brand: "RTP",
    quantity: "1 шт",
    price: 180,
    allResidual: 0,
    residualValue: "",
    unit: "шт",
    isActive: false,
    category: "fitingPPR",
  },
  {
    id: 97,
    img: trubaRtp,
    name: "Муфта комбинированная разъемная (американка) с Н\\Р PPR 25х1 PN25 белый RTP",
    brand: "RTP",
    quantity: "100 шт",
    price: 220,
    allResidual: 500,
    residualValue: "",
    unit: "шт",
    isActive: true,
    category: "fitingPPR",
  },
  {
    id: 98,
    img: trubaRtp,
    name: "Муфта комбинированная разъемная (американка) с В\\Р PPR 32х1 PN25 белый RTP",
    brand: "RTP",
    quantity: "1 шт",
    price: 190,
    allResidual: 0,
    residualValue: "",
    unit: "шт",
    isActive: false,
    category: "fitingPPR",
  },
  {
    id: 99,
    img: trubaRtp,
    name: "Муфта комбинированная разъемная (американка) с Н\\Р PPR 32х1 PN25 белый RTP",
    brand: "RTP",
    quantity: "1 шт",
    price: 210,
    allResidual: 0,
    residualValue: "",
    unit: "шт",
    isActive: false,
    category: "fitingPPR",
  },
  {
    id: 100,
    img: trubaRtp,
    name: "Муфта комбинированная разъемная (американка) с В\\Р PPR 40х1 1\\4 PN25 белый RTP",
    brand: "RTP",
    quantity: "1 шт",
    price: 380,
    allResidual: 0,
    residualValue: "",
    unit: "шт",
    isActive: false,
    category: "fitingPPR",
  },
  {
    id: 101,
    img: trubaRtp,
    name: "Муфта комбинированная разъемная (американка) с Н\\Р PPR 40х1 1\\4 PN25 белый RTP",
    brand: "RTP",
    quantity: "1 шт",
    price: 450,
    allResidual: 0,
    residualValue: "",
    unit: "шт",
    isActive: false,
    category: "fitingPPR",
  },
  {
    id: 102,
    img: trubaRtp,
    name: "Муфта комбинированная разъемная (американка) с В\\Р PPR 50х1 1\\2 PN25 белый RTP",
    brand: "RTP",
    quantity: "1 шт",
    price: 500,
    allResidual: 0,
    residualValue: "",
    unit: "шт",
    isActive: false,
    category: "fitingPPR",
  },
  {
    id: 103,
    img: trubaRtp,
    name: "Муфта комбинированная разъемная (американка) с Н\\Р PPR 40х1 1\\2 PN25 белый RTP",
    brand: "RTP",
    quantity: "1 шт",
    price: 590,
    allResidual: 0,
    residualValue: "",
    unit: "шт",
    isActive: false,
    category: "fitingPPR",
  },

  // ==================== МУФТА ПЕРЕХОДНАЯ ====================
  {
    id: 104,
    img: trubaRtp,
    name: "Муфта переходная PPR ВР\\НР 25\\20 PN25 белый RTP",
    brand: "RTP",
    quantity: "1 шт",
    price: 5,
    allResidual: 0,
    residualValue: "",
    unit: "шт",
    isActive: false,
    category: "fitingPPR",
  },
  {
    id: 105,
    img: trubaRtp,
    name: "Муфта переходная PPR ВР\\НР 32\\20 PN25 белый RTP",
    brand: "RTP",
    quantity: "1 шт",
    price: 7,
    allResidual: 0,
    residualValue: "",
    unit: "шт",
    isActive: false,
    category: "fitingPPR",
  },
  {
    id: 106,
    img: trubaRtp,
    name: "Муфта переходная PPR ВР\\НР 32\\25 PN25 белый RTP",
    brand: "RTP",
    quantity: "1 шт",
    price: 7,
    allResidual: 0,
    residualValue: "",
    unit: "шт",
    isActive: false,
    category: "fitingPPR",
  },
  {
    id: 107,
    img: trubaRtp,
    name: "Муфта переходная PPR ВР\\НР 40\\20 PN25 белый RTP",
    brand: "RTP",
    quantity: "1 шт",
    price: 12,
    allResidual: 0,
    residualValue: "",
    unit: "шт",
    isActive: false,
    category: "fitingPPR",
  },
  {
    id: 108,
    img: trubaRtp,
    name: "Муфта переходная PPR ВР\\НР 40\\25 PN25 белый RTP",
    brand: "RTP",
    quantity: "1 шт",
    price: 15,
    allResidual: 0,
    residualValue: "",
    unit: "шт",
    isActive: false,
    category: "fitingPPR",
  },
  {
    id: 109,
    img: trubaRtp,
    name: "Муфта переходная PPR ВР\\НР 40\\32 PN25 белый RTP",
    brand: "RTP",
    quantity: "1 шт",
    price: 15,
    allResidual: 0,
    residualValue: "",
    unit: "шт",
    isActive: false,
    category: "fitingPPR",
  },
  {
    id: 110,
    img: trubaRtp,
    name: "Муфта переходная PPR ВР\\ВР 25\\20 PN25 белый RTP",
    brand: "RTP",
    quantity: "1 шт",
    price: 8,
    allResidual: 0,
    residualValue: "",
    unit: "шт",
    isActive: false,
    category: "fitingPPR",
  },
  {
    id: 111,
    img: trubaRtp,
    name: "Муфта переходная PPR ВР\\ВР 32\\20 PN25 белый RTP",
    brand: "RTP",
    quantity: "1 шт",
    price: 15,
    allResidual: 0,
    residualValue: "",
    unit: "шт",
    isActive: false,
    category: "fitingPPR",
  },
  {
    id: 112,
    img: trubaRtp,
    name: "Муфта переходная PPR ВР\\ВР 32\\25 PN25 белый RTP",
    brand: "RTP",
    quantity: "1 шт",
    price: 17,
    allResidual: 0,
    residualValue: "",
    unit: "шт",
    isActive: false,
    category: "fitingPPR",
  },
  {
    id: 113,
    img: trubaRtp,
    name: "Муфта переходная PPR ВР\\ВР 40\\32 PN25 белый RTP",
    brand: "RTP",
    quantity: "1 шт",
    price: 20,
    allResidual: 0,
    residualValue: "",
    unit: "шт",
    isActive: false,
    category: "fitingPPR",
  },

  // ==================== ОБРАТНЫЙ КЛАПАН PPR ====================
  {
    id: 114,
    img: trubaRtp,
    name: "Обратный клапан 20ф PN25 белый RTP",
    brand: "RTP",
    quantity: "1 шт",
    price: 100,
    allResidual: 0,
    residualValue: "",
    unit: "шт",
    isActive: false,
    category: "fitingPPR",
  },
  {
    id: 115,
    img: trubaRtp,
    name: "Обратный клапан 25ф PN25 белый RTP",
    brand: "RTP",
    quantity: "1 шт",
    price: 120,
    allResidual: 0,
    residualValue: "",
    unit: "шт",
    isActive: false,
    category: "fitingPPR",
  },
  {
    id: 116,
    img: trubaRtp,
    name: "Обратный клапан 32ф PN25 белый RTP",
    brand: "RTP",
    quantity: "12 шт",
    price: 180,
    allResidual: 111,
    residualValue: "",
    unit: "шт",
    isActive: true,
    category: "fitingPPR",
  },

  // ==================== ТРОЙНИК КОМБИНИРОВАННЫЙ ====================
  {
    id: 117,
    img: trubaRtp,
    name: "Тройник комбинированный с В\\Р 20х1\\2 PN25 белый RTP",
    brand: "RTP",
    quantity: "1 шт",
    price: 50,
    allResidual: 0,
    residualValue: "",
    unit: "шт",
    isActive: false,
    category: "fitingPPR",
  },
  {
    id: 118,
    img: trubaRtp,
    name: "Тройник комбинированный с В\\Р 25х1\\2 PN25 белый RTP",
    brand: "RTP",
    quantity: "1 шт",
    price: 65,
    allResidual: 0,
    residualValue: "",
    unit: "шт",
    isActive: false,
    category: "fitingPPR",
  },
  {
    id: 119,
    img: trubaRtp,
    name: "Тройник комбинированный с В\\Р 32х1\\2 PN25 белый RTP",
    brand: "RTP",
    quantity: "1 шт",
    price: 70,
    allResidual: 0,
    residualValue: "",
    unit: "шт",
    isActive: false,
    category: "fitingPPR",
  },
  {
    id: 120,
    img: trubaRtp,
    name: "Тройник комбинированный с В\\Р 25х3\\4 PN25 белый RTP",
    brand: "RTP",
    quantity: "1 шт",
    price: 75,
    allResidual: 0,
    residualValue: "",
    unit: "шт",
    isActive: false,
    category: "fitingPPR",
  },
  {
    id: 121,
    img: trubaRtp,
    name: "Тройник комбинированный с Н\\Р 20х1\\2 PN25 белый RTP",
    brand: "RTP",
    quantity: "1 шт",
    price: 60,
    allResidual: 0,
    residualValue: "",
    unit: "шт",
    isActive: false,
    category: "fitingPPR",
  },
  {
    id: 122,
    img: trubaRtp,
    name: "Тройник комбинированный с Н\\Р 25х1\\2 PN25 белый RTP",
    brand: "RTP",
    quantity: "1 шт",
    price: 70,
    allResidual: 0,
    residualValue: "",
    unit: "шт",
    isActive: false,
    category: "fitingPPR",
  },
  {
    id: 123,
    img: trubaRtp,
    name: "Тройник комбинированный с Н\\Р 25х3\\4 PN25 белый RTP",
    brand: "RTP",
    quantity: "1 шт",
    price: 80,
    allResidual: 0,
    residualValue: "",
    unit: "шт",
    isActive: false,
    category: "fitingPPR",
  },
  {
    id: 124,
    img: trubaRtp,
    name: "Тройник комбинированный с Н\\Р 32х1\\2 PN25 белый RTP",
    brand: "RTP",
    quantity: "1 шт",
    price: 85,
    allResidual: 0,
    residualValue: "",
    unit: "шт",
    isActive: false,
    category: "fitingPPR",
  },

  // ==================== ТРУБА PERT truba metal i skoba ====================
  {
    id: 125,
    img: trubaRtp,
    name: "Труба PERT 16х2.0х100 красный RTP",
    brand: "RTP",
    quantity: "1 шт",
    price: 24,
    allResidual: 0,
    residualValue: "",
    unit: "м",
    isActive: false,
    category: "other",
  },
  {
    id: 126,
    img: trubaRtp,
    name: "Труба PERT 16х2.200 красный RTP",
    brand: "RTP",
    quantity: "1 шт",
    price: 24,
    allResidual: 0,
    residualValue: "",
    unit: "м",
    isActive: false,
    category: "other",
  },
  {
    id: 127,
    img: trubaRtp,
    name: "Труба PERT 16х2.0х600 красный RTP",
    brand: "RTP",
    quantity: "1 шт",
    price: 24,
    allResidual: 0,
    residualValue: "",
    unit: "м",
    isActive: false,
    category: "other",
  },
  {
    id: 128,
    img: trubaRtp,
    name: "Труба PERT 16х2.0х100 серый RTP",
    brand: "RTP",
    quantity: "1 шт",
    price: 24,
    allResidual: 0,
    residualValue: "",
    unit: "м",
    isActive: false,
    category: "other",
  },
  {
    id: 129,
    img: trubaRtp,
    name: "Труба PERT 16х2.0х200 серый RTP",
    brand: "RTP",
    quantity: "1 шт",
    price: 24,
    allResidual: 0,
    residualValue: "",
    unit: "м",
    isActive: false,
    category: "other",
  },
  {
    id: 333333,
    img: trubaRtp,
    name: "Труба металлопластиковая PERT-AL-PERT 16х2,0х200, белый, РТП",
    brand: "RTP",
    quantity: "200м",
    price: 90,
    allResidual: 5000,
    residualValue: "",
    isActive: true,
    unit: "м",
    category: "other",
  },
  {
    id: 333334,
    img: trubaRtp,
    name: "Длинные скобы для теплого пола (16-20) RTP",
    brand: "RTP",
    quantity: "1000 шт",
    price: 2.5,
    allResidual: 120000,
    residualValue: "",
    isActive: true,
    unit: "шт",
    category: "other",
  },

  // ==================== ТРУБА ВК ПП ====================
  {
    id: 130,
    img: trubaRtp,
    name: "Труба ВК ПП 50х1,8х250 серый RTP",
    brand: "RTP",
    quantity: "1 шт",
    price: 45,
    allResidual: 0,
    residualValue: "",
    unit: "м",
    isActive: false,
    category: "trubaVK_NK",
  },
  {
    id: 131,
    img: trubaRtp,
    name: "Труба ВК ПП 50х1,8х500 серый RTP",
    brand: "RTP",
    quantity: "60 шт",
    price: 60,
    allResidual: 120,
    residualValue: "",
    unit: "м",
    isActive: true,
    category: "trubaVK_NK",
  },
  {
    id: 132,
    img: trubaRtp,
    name: "Труба ВК ПП 50х1,8х1000 серый RTP",
    brand: "RTP",
    quantity: "10 шт",
    price: 95,
    allResidual: 750,
    residualValue: "",
    unit: "м",
    isActive: true,
    category: "trubaVK_NK",
  },
  {
    id: 133,
    img: trubaRtp,
    name: "Труба ВК ПП 50х1,8х2000 серый RTP",
    brand: "RTP",
    quantity: "1 шт",
    price: 160,
    allResidual: 0,
    residualValue: "",
    unit: "м",
    isActive: false,
    category: "trubaVK_NK",
  },
  {
    id: 134,
    img: trubaRtp,
    name: "Труба ВК ПП 50х1,8х3000 серый RTP",
    brand: "RTP",
    quantity: "1 шт",
    price: 240,
    allResidual: 0,
    residualValue: "",
    unit: "м",
    isActive: false,
    category: "trubaVK_NK",
  },
  {
    id: 135,
    img: trubaRtp,
    name: "Труба ВК ПП 76х2.7х1000 серый RTP",
    brand: "RTP",
    quantity: "1 шт",
    price: 165,
    allResidual: 0,
    residualValue: "",
    unit: "м",
    isActive: false,
    category: "trubaVK_NK",
  },
  {
    id: 136,
    img: trubaRtp,
    name: "Труба ВК ПП 76х2.7х2000 серый RTP",
    brand: "RTP",
    quantity: "1 шт",
    price: 300,
    allResidual: 0,
    residualValue: "",
    unit: "м",
    isActive: false,
    category: "trubaVK_NK",
  },
  {
    id: 137,
    img: trubaRtp,
    name: "Труба ВК ПП 76х2.7х3000 серый RTP",
    brand: "RTP",
    quantity: "1 шт",
    price: 450,
    allResidual: 0,
    residualValue: "",
    unit: "м",
    isActive: false,
    category: "trubaVK_NK",
  },
  {
    id: 138,
    img: trubaRtp,
    name: "Труба ВК ПП 110х2.7х250 серый RTP",
    brand: "RTP",
    quantity: "1 шт",
    price: 105,
    allResidual: 0,
    residualValue: "",
    unit: "м",
    isActive: false,
    category: "trubaVK_NK",
  },
  {
    id: 139,
    img: trubaRtp,
    name: "Труба ВК ПП 110х2.7х500 серый RTP",
    brand: "RTP",
    quantity: "10 шт",
    price: 160,
    allResidual: 580,
    residualValue: "",
    unit: "м",
    isActive: true,
    category: "trubaVK_NK",
  },
  {
    id: 140,
    img: trubaRtp,
    name: "Труба ВК ПП 110х2.7х1000 серый RTP",
    brand: "RTP",
    quantity: "10 шт",
    price: 260,
    allResidual: 300,
    residualValue: "",
    unit: "м",
    isActive: true,
    category: "trubaVK_NK",
  },
  {
    id: 141,
    img: trubaRtp,
    name: "Труба ВК ПП 110х2.7х2000 серый RTP",
    brand: "RTP",
    quantity: "1 шт",
    price: 460,
    allResidual: 0,
    residualValue: "",
    unit: "м",
    isActive: false,
    category: "trubaVK_NK",
  },
  {
    id: 142,
    img: trubaRtp,
    name: "Труба ВК ПП 110х2.7х3000 серый RTP",
    brand: "RTP",
    quantity: "10 шт",
    price: 690,
    allResidual: 270,
    residualValue: "",
    unit: "м",
    isActive: true,
    category: "trubaVK_NK",
  },

  // ==================== ТРУБА НК ПП ====================
  {
    id: 143,
    img: trubaRtp,
    name: "Труба НК ПП 110х3.4х500 рыжый RTP",
    brand: "RTP",
    quantity: "1 шт",
    price: 180,
    allResidual: 0,
    residualValue: "",
    unit: "м",
    isActive: false,
    category: "trubaVK_NK",
  },
  {
    id: 144,
    img: trubaRtp,
    name: "Труба НК ПП 110х3.4х1000 рыжый RTP",
    brand: "RTP",
    quantity: "10 шт",
    price: 300,
    allResidual: 60,
    residualValue: "",
    unit: "м",
    isActive: true,
    category: "trubaVK_NK",
  },
  {
    id: 145,
    img: trubaRtp,
    name: "Труба НК ПП 110х3.4х2000 рыжый RTP",
    brand: "RTP",
    quantity: "1 шт",
    price: 570,
    allResidual: 0,
    residualValue: "",
    unit: "м",
    isActive: false,
    category: "trubaVK_NK",
  },
  {
    id: 146,
    img: trubaRtp,
    name: "Труба НК ПП 110х3.4х3000 рыжый RTP",
    brand: "RTP",
    quantity: "1 шт",
    price: 860,
    allResidual: 0,
    residualValue: "",
    unit: "м",
    isActive: false,
    category: "trubaVK_NK",
  },
  {
    id: 147,
    img: trubaRtp,
    name: "Труба НК ПП 160х4,9х500 рыжый RTP",
    brand: "RTP",
    quantity: "2 шт",
    price: 380,
    allResidual: 236,
    residualValue: "",
    unit: "м",
    isActive: true,
    category: "trubaVK_NK",
  },
  {
    id: 148,
    img: trubaRtp,
    name: "Труба НК ПП 160х4,9х1000 рыжый RTP",
    brand: "RTP",
    quantity: "2 шт",
    price: 650,
    allResidual: 254,
    residualValue: "",
    unit: "м",
    isActive: true,
    category: "trubaVK_NK",
  },
  {
    id: 149,
    img: trubaRtp,
    name: "Труба НК ПП 160х4,9х2000 рыжый RTP",
    brand: "RTP",
    quantity: "2 шт",
    price: 1200,
    allResidual: 200,
    residualValue: "",
    unit: "м",
    isActive: true,
    category: "trubaVK_NK",
  },
  {
    id: 150,
    img: trubaRtp,
    name: "Труба НК ПП 160х4,9х3000 рыжый RTP",
    brand: "RTP",
    quantity: "2 шт",
    price: 1800,
    allResidual: 280,
    residualValue: "",
    unit: "м",
    isActive: true,
    category: "trubaVK_NK",
  },

  // ==================== ПОТРУБОК / ГОФРА ====================
  {
    id: 151,
    img: trubaRtp,
    name: "Потрубок компенсационный ВК ПП 110х87 К,серый RTP",
    brand: "RTP",
    quantity: "36 шт",
    price: 100,
    allResidual: 108,
    residualValue: "",
    unit: "шт",
    isActive: true,
    category: "trubaVK_NK",
  },
  {
    id: 152,
    img: trubaRtp,
    name: "Потрубок компенсационный ВК ПП 50х87 К,серый RTP",
    brand: "RTP",
    quantity: "1 шт",
    price: 50,
    allResidual: 0,
    residualValue: "",
    unit: "шт",
    isActive: false,
    category: "trubaVK_NK",
  },
  {
    id: 153,
    img: trubaRtp,
    name: "Потрубок гофра ВК ПП 50х87 К,серый RTP",
    brand: "RTP",
    quantity: "1 шт",
    price: 50,
    allResidual: 0,
    residualValue: "",
    unit: "шт",
    isActive: false,
    category: "trubaVK_NK",
  },

  // ==================== ОТВОДЫ ВК/НК ====================
  {
    id: 154,
    img: trubaRtp,
    name: "Отвод ВК ПП 50х45 К,серый RTP",
    brand: "RTP",
    quantity: "1 шт",
    price: 23,
    allResidual: 0,
    residualValue: "",
    unit: "шт",
    isActive: false,
    category: "trubaVK_NK",
  },
  {
    id: 155,
    img: trubaRtp,
    name: "Отвод ВК ПП 50х87 К,серый RTP",
    brand: "RTP",
    quantity: "1 шт",
    price: 21,
    allResidual: 0,
    residualValue: "",
    unit: "шт",
    isActive: false,
    category: "trubaVK_NK",
  },
  {
    id: 156,
    img: trubaRtp,
    name: "Отвод ВК ПП 75х45 К,серый RTP",
    brand: "RTP",
    quantity: "1 шт",
    price: 55,
    allResidual: 0,
    residualValue: "",
    unit: "шт",
    isActive: false,
    category: "trubaVK_NK",
  },
  {
    id: 157,
    img: trubaRtp,
    name: "Отвод ВК ПП 75х87 К,серый RTP",
    brand: "RTP",
    quantity: "1 шт",
    price: 60,
    allResidual: 0,
    residualValue: "",
    unit: "шт",
    isActive: false,
    category: "trubaVK_NK",
  },
  {
    id: 158,
    img: trubaRtp,
    name: "Отвод ВК ПП 110х87 К,серый RTP",
    brand: "RTP",
    quantity: "1 шт",
    price: 85,
    allResidual: 0,
    residualValue: "",
    unit: "шт",
    isActive: false,
    category: "trubaVK_NK",
  },
  {
    id: 159,
    img: trubaRtp,
    name: "Отвод ВК ПП 110х45° К,серый RTP",
    brand: "RTP",
    quantity: "1 шт",
    price: 75,
    allResidual: 0,
    residualValue: "",
    unit: "шт",
    isActive: false,
    category: "trubaVK_NK",
  },
  {
    id: 160,
    img: trubaRtp,
    name: "Отвод ВК ПП 110х15° К,серый RTP",
    brand: "RTP",
    quantity: "1 шт",
    price: 75,
    allResidual: 0,
    residualValue: "",
    unit: "шт",
    isActive: false,
    category: "trubaVK_NK",
  },
  {
    id: 161,
    img: trubaRtp,
    name: "Отвод ВК ПП 110х30° К,серый RTP",
    brand: "RTP",
    quantity: "1 шт",
    price: 75,
    allResidual: 0,
    residualValue: "",
    unit: "шт",
    isActive: false,
    category: "trubaVK_NK",
  },
  {
    id: 162,
    img: trubaRtp,
    name: "Отвод ВК ПП 110х67° К,серый RTP",
    brand: "RTP",
    quantity: "1 шт",
    price: 75,
    allResidual: 0,
    residualValue: "",
    unit: "шт",
    isActive: false,
    category: "trubaVK_NK",
  },
  {
    id: 163,
    img: trubaRtp,
    name: "Отвод НК ПП 110х15° К,серый RTP",
    brand: "RTP",
    quantity: "1 шт",
    price: 75,
    allResidual: 0,
    residualValue: "",
    unit: "шт",
    isActive: false,
    category: "trubaVK_NK",
  },
  {
    id: 164,
    img: trubaRtp,
    name: "Отвод НК ПП 110х87 К,рыжый RTP",
    brand: "RTP",
    quantity: "35 шт",
    price: 90,
    allResidual: 350,
    residualValue: "",
    unit: "шт",
    isActive: true,
    category: "trubaVK_NK",
  },
  {
    id: 165,
    img: trubaRtp,
    name: "Отвод НК ПП 110х45° К,рыжый RTP",
    brand: "RTP",
    quantity: "1 шт",
    price: 80,
    allResidual: 0,
    residualValue: "",
    unit: "шт",
    isActive: false,
    category: "trubaVK_NK",
  },
  {
    id: 166,
    img: trubaRtp,
    name: "Отвод НК ПП 160х87 К,рыжый RTP",
    brand: "RTP",
    quantity: "1 шт",
    price: 400,
    allResidual: 0,
    residualValue: "",
    unit: "шт",
    isActive: false,
    category: "trubaVK_NK",
  },
  {
    id: 167,
    img: trubaRtp,
    name: "Отвод НК ПП 160х45° К,рыжый RTP",
    brand: "RTP",
    quantity: "1 шт",
    price: 250,
    allResidual: 0,
    residualValue: "",
    unit: "шт",
    isActive: false,
    category: "trubaVK_NK",
  },

  // ==================== ТРОЙНИКИ ВК/НК ====================
  {
    id: 168,
    img: trubaRtp,
    name: "Тройник ВК ПП 50\\50\\45° К,серый RTP",
    brand: "RTP",
    quantity: "1 шт",
    price: 50,
    allResidual: 0,
    residualValue: "",
    unit: "шт",
    isActive: false,
    category: "trubaVK_NK",
  },
  {
    id: 169,
    img: trubaRtp,
    name: "Тройник ВК ПП 50\\50\\87° К,серый RTP",
    brand: "RTP",
    quantity: "1 шт",
    price: 50,
    allResidual: 0,
    residualValue: "",
    unit: "шт",
    isActive: false,
    category: "trubaVK_NK",
  },
  {
    id: 170,
    img: trubaRtp,
    name: "Тройник ВК ПП 75\\50\\45° К,серый RTP",
    brand: "RTP",
    quantity: "1 шт",
    price: 80,
    allResidual: 0,
    residualValue: "",
    unit: "шт",
    isActive: false,
    category: "trubaVK_NK",
  },
  {
    id: 171,
    img: trubaRtp,
    name: "Тройник ВК ПП 75\\50\\87° К,серый RTP",
    brand: "RTP",
    quantity: "1 шт",
    price: 80,
    allResidual: 0,
    residualValue: "",
    unit: "шт",
    isActive: false,
    category: "trubaVK_NK",
  },
  {
    id: 172,
    img: trubaRtp,
    name: "Тройник ВК ПП 75\\75\\45° К,серый RTP",
    brand: "RTP",
    quantity: "25 шт",
    price: 80,
    allResidual: 150,
    residualValue: "",
    unit: "шт",
    isActive: true,
    category: "trubaVK_NK",
  },
  {
    id: 173,
    img: trubaRtp,
    name: "Тройник ВК ПП 75\\75\\87° К,серый RTP",
    brand: "RTP",
    quantity: "1 шт",
    price: 80,
    allResidual: 0,
    residualValue: "",
    unit: "шт",
    isActive: false,
    category: "trubaVK_NK",
  },
  {
    id: 174,
    img: trubaRtp,
    name: "Тройник ВК ПП 110\\110\\87° К,серый RTP",
    brand: "RTP",
    quantity: "1 шт",
    price: 135,
    allResidual: 0,
    residualValue: "",
    unit: "шт",
    isActive: false,
    category: "trubaVK_NK",
  },
  {
    id: 175,
    img: trubaRtp,
    name: "Тройник ВК ПП 110\\110\\45° К,серый RTP",
    brand: "RTP",
    quantity: "1 шт",
    price: 145,
    allResidual: 0,
    residualValue: "",
    unit: "шт",
    isActive: false,
    category: "trubaVK_NK",
  },
  {
    id: 176,
    img: trubaRtp,
    name: "Тройник ВК ПП 110\\50\\87° К,серый RTP",
    brand: "RTP",
    quantity: "1 шт",
    price: 95,
    allResidual: 0,
    residualValue: "",
    unit: "шт",
    isActive: false,
    category: "trubaVK_NK",
  },
  {
    id: 177,
    img: trubaRtp,
    name: "Тройник ВК ПП 110\\50\\45° К,серый RTP",
    brand: "RTP",
    quantity: "1 шт",
    price: 100,
    allResidual: 0,
    residualValue: "",
    unit: "шт",
    isActive: false,
    category: "trubaVK_NK",
  },
  {
    id: 178,
    img: trubaRtp,
    name: "Тройник ВК ПП 110\\76\\87° К,серый RTP",
    brand: "RTP",
    quantity: "1 шт",
    price: 135,
    allResidual: 0,
    residualValue: "",
    unit: "шт",
    isActive: false,
    category: "trubaVK_NK",
  },
  {
    id: 179,
    img: trubaRtp,
    name: "Тройник ВК ПП 110\\76\\45° К,серый RTP",
    brand: "RTP",
    quantity: "1 шт",
    price: 145,
    allResidual: 0,
    residualValue: "",
    unit: "шт",
    isActive: false,
    category: "trubaVK_NK",
  },
  {
    id: 180,
    img: trubaRtp,
    name: "Тройник НК ПП 110\\110\\87 К,рыжый RTP",
    brand: "RTP",
    quantity: "1 шт",
    price: 140,
    allResidual: 0,
    residualValue: "",
    unit: "шт",
    isActive: false,
    category: "trubaVK_NK",
  },
  {
    id: 181,
    img: trubaRtp,
    name: "Тройник НК ПП 110\\110\\45 К,рыжый RTP",
    brand: "RTP",
    quantity: "1 шт",
    price: 150,
    allResidual: 0,
    residualValue: "",
    unit: "шт",
    isActive: false,
    category: "trubaVK_NK",
  },
  {
    id: 182,
    img: trubaRtp,
    name: "Тройник НК ПП 160\\160\\87 К,рыжый RTP",
    brand: "RTP",
    quantity: "1 шт",
    price: 550,
    allResidual: 0,
    residualValue: "",
    unit: "шт",
    isActive: false,
    category: "trubaVK_NK",
  },
  {
    id: 183,
    img: trubaRtp,
    name: "Тройник НК ПП 160\\160\\45 К,рыжый RTP",
    brand: "RTP",
    quantity: "1 шт",
    price: 650,
    allResidual: 0,
    residualValue: "",
    unit: "шт",
    isActive: false,
    category: "trubaVK_NK",
  },
  {
    id: 184,
    img: trubaRtp,
    name: "Тройник НК ПП 160\\110х87 К,рыжый RTP",
    brand: "RTP",
    quantity: "1 шт",
    price: 450,
    allResidual: 0,
    residualValue: "",
    unit: "шт",
    isActive: false,
    category: "trubaVK_NK",
  },

  // ==================== РЕВИЗИЯ С КРЫШКОЙ ====================
  {
    id: 185,
    img: trubaRtp,
    name: "Ревизия с крышкой НК ПП 50х87° К,серый RTP",
    brand: "RTP",
    quantity: "1 шт",
    price: 80,
    allResidual: 0,
    residualValue: "",
    unit: "шт",
    isActive: false,
    category: "trubaVK_NK",
  },
  {
    id: 186,
    img: trubaRtp,
    name: "Ревизия с крышкой НК ПП 76х87° К,серый RTP",
    brand: "RTP",
    quantity: "1 шт",
    price: 120,
    allResidual: 0,
    residualValue: "",
    unit: "шт",
    isActive: false,
    category: "trubaVK_NK",
  },
  {
    id: 187,
    img: trubaRtp,
    name: "Ревизия с крышкой НК ПП 110х87° К,серый RTP",
    brand: "RTP",
    quantity: "36 шт",
    price: 155,
    allResidual: 288,
    residualValue: "",
    unit: "шт",
    isActive: true,
    category: "trubaVK_NK",
  },
  {
    id: 188,
    img: trubaRtp,
    name: "Ревизия с крышкой НК ПП 110х87° К,рыжый RTP",
    brand: "RTP",
    quantity: "1 шт",
    price: 165,
    allResidual: 0,
    residualValue: "",
    unit: "шт",
    isActive: false,
    category: "trubaVK_NK",
  },
  {
    id: 189,
    img: trubaRtp,
    name: "Ревизия с крышкой НК ПП 160\\110х87° К,рыжый RTP",
    brand: "RTP",
    quantity: "1 шт",
    price: 650,
    allResidual: 0,
    residualValue: "",
    unit: "шт",
    isActive: false,
    category: "trubaVK_NK",
  },
  {
    id: 190,
    img: trubaRtp,
    name: "Ревизия с крышкой НК ПП 160х87° К,рыжый RTP",
    brand: "RTP",
    quantity: "1 шт",
    price: 650,
    allResidual: 0,
    residualValue: "",
    unit: "шт",
    isActive: false,
    category: "trubaVK_NK",
  },

  // ==================== ЗАГЛУШКА ВК/НК ====================
  {
    id: 191,
    img: trubaRtp,
    name: "Заглушка ВК ПП 110х87° К,серый RTP",
    brand: "RTP",
    quantity: "1 шт",
    price: 25,
    allResidual: 0,
    residualValue: "",
    unit: "шт",
    isActive: false,
    category: "trubaVK_NK",
  },
  {
    id: 192,
    img: trubaRtp,
    name: "Заглушка ВК ПП 76х87° К,серый RTP",
    brand: "RTP",
    quantity: "1 шт",
    price: 22,
    allResidual: 0,
    residualValue: "",
    unit: "шт",
    isActive: false,
    category: "trubaVK_NK",
  },
  {
    id: 193,
    img: trubaRtp,
    name: "Заглушка ВК ПП 50х87° К,серый RTP",
    brand: "RTP",
    quantity: "1 шт",
    price: 13,
    allResidual: 0,
    residualValue: "",
    unit: "шт",
    isActive: false,
    category: "trubaVK_NK",
  },
  {
    id: 194,
    img: trubaRtp,
    name: "Заглушка НК ПП 110х87° К,рыжый RTP",
    brand: "RTP",
    quantity: "1 шт",
    price: 30,
    allResidual: 0,
    residualValue: "",
    unit: "шт",
    isActive: false,
    category: "trubaVK_NK",
  },
  {
    id: 195,
    img: trubaRtp,
    name: "Заглушка НК ПП 160х87° К,рыжый RTP",
    brand: "RTP",
    quantity: "1 шт",
    price: 120,
    allResidual: 0,
    residualValue: "",
    unit: "шт",
    isActive: false,
    category: "trubaVK_NK",
  },

  // ==================== МУФТЫ ВК/НК ====================
  {
    id: 196,
    img: trubaRtp,
    name: "Муфта гибкая ВК ПП 50х87° К,серый RTP",
    brand: "RTP",
    quantity: "1 шт",
    price: 25,
    allResidual: 0,
    residualValue: "",
    unit: "шт",
    isActive: false,
    category: "trubaVK_NK",
  },
  {
    id: 197,
    img: trubaRtp,
    name: "Муфта двухраструбная ВК ПП 50х87° К,серый RTP",
    brand: "RTP",
    quantity: "1 шт",
    price: 25,
    allResidual: 0,
    residualValue: "",
    unit: "шт",
    isActive: false,
    category: "trubaVK_NK",
  },
  {
    id: 198,
    img: trubaRtp,
    name: "Муфта двухраструбная ВК ПП 76х87° К,серый RTP",
    brand: "RTP",
    quantity: "1 шт",
    price: 60,
    allResidual: 0,
    residualValue: "",
    unit: "шт",
    isActive: false,
    category: "trubaVK_NK",
  },
  {
    id: 199,
    img: trubaRtp,
    name: "Муфта двухраструбная ВК ПП 110х87° К,серый RTP",
    brand: "RTP",
    quantity: "1 шт",
    price: 75,
    allResidual: 0,
    residualValue: "",
    unit: "шт",
    isActive: false,
    category: "trubaVK_NK",
  },
  {
    id: 200,
    img: trubaRtp,
    name: "Муфта двухраструбная НК ПП 110х87° К,рыжый RTP",
    brand: "RTP",
    quantity: "1 шт",
    price: 80,
    allResidual: 0,
    residualValue: "",
    unit: "шт",
    isActive: false,
    category: "trubaVK_NK",
  },
  {
    id: 201,
    img: trubaRtp,
    name: "Муфта двухраструбная НК ПП 160х87° К,рыжый RTP",
    brand: "RTP",
    quantity: "1 шт",
    price: 350,
    allResidual: 0,
    residualValue: "",
    unit: "шт",
    isActive: false,
    category: "trubaVK_NK",
  },

  // ==================== РЕДУКЦИЯ ====================
  {
    id: 202,
    img: trubaRtp,
    name: "Редукция ВК ПП 76\\50 К,серый RTP",
    brand: "RTP",
    quantity: "1 шт",
    price: 45,
    allResidual: 0,
    residualValue: "",
    unit: "шт",
    isActive: false,
    category: "trubaVK_NK",
  },
  {
    id: 203,
    img: trubaRtp,
    name: "Редукция ВК ПП 110\\50 К,серый RTP",
    brand: "RTP",
    quantity: "60 шт",
    price: 60,
    allResidual: 660,
    residualValue: "",
    unit: "шт",
    isActive: true,
    category: "trubaVK_NK",
  },
  {
    id: 204,
    img: trubaRtp,
    name: "Редукция ВК ПП 110\\76 К,серый RTP",
    brand: "RTP",
    quantity: "1 шт",
    price: 80,
    allResidual: 0,
    residualValue: "",
    unit: "шт",
    isActive: false,
    category: "trubaVK_NK",
  },
  {
    id: 205,
    img: trubaRtp,
    name: "Редукция НК ПП 160\\110 К,серый RTP",
    brand: "RTP",
    quantity: "1 шт",
    price: 230,
    allResidual: 0,
    residualValue: "",
    unit: "шт",
    isActive: false,
    category: "trubaVK_NK",
  },
  {
    id: 206,
    img: trubaRtp,
    name: "Переход с Чугуна на пластик ВК ПП 100\\120 К,серый RTP",
    brand: "RTP",
    quantity: "1 шт",
    price: 250,
    allResidual: 0,
    residualValue: "",
    unit: "шт",
    isActive: false,
    category: "trubaVK_NK",
  },

  // ==================== ЗОНТ ====================
  {
    id: 207,
    img: trubaRtp,
    name: "Зонт ВК ПП 110х87 К,серый RTP",
    brand: "RTP",
    quantity: "1 шт",
    price: 95,
    allResidual: 0,
    residualValue: "",
    unit: "шт",
    isActive: false,
    category: "trubaVK_NK",
  },
  {
    id: 208,
    img: trubaRtp,
    name: "Зонт ВК ПП 50х87 К,серый RTP",
    brand: "RTP",
    quantity: "1 шт",
    price: 60,
    allResidual: 0,
    residualValue: "",
    unit: "шт",
    isActive: false,
    category: "trubaVK_NK",
  },

  // ==================== КРЕСТОВИНА ====================
  {
    id: 209,
    img: trubaRtp,
    name: "Крестовина двухплоскостная ВК ПП 110\\110\\50 45° К,серый RTP лев.",
    brand: "RTP",
    quantity: "1 шт",
    price: 210,
    allResidual: 0,
    residualValue: "",
    unit: "шт",
    isActive: false,
    category: "trubaVK_NK",
  },
  {
    id: 210,
    img: trubaRtp,
    name: "Крестовина двухплоскостная ВК ПП 110\\110\\50 45° К,серый RTP пра.",
    brand: "RTP",
    quantity: "1 шт",
    price: 210,
    allResidual: 0,
    residualValue: "",
    unit: "шт",
    isActive: false,
    category: "trubaVK_NK",
  },
  {
    id: 211,
    img: trubaRtp,
    name: "Крестовина двухплоскостная ВК ПП 110\\110\\50 45° К,серый RTP",
    brand: "RTP",
    quantity: "1 шт",
    price: 250,
    allResidual: 0,
    residualValue: "",
    unit: "шт",
    isActive: false,
    category: "trubaVK_NK",
  },
  {
    id: 212,
    img: trubaRtp,
    name: "Крестовина одноплоскостная ВК ПП 110\\110\\100 87° К,серый RTP",
    brand: "RTP",
    quantity: "1 шт",
    price: 220,
    allResidual: 0,
    residualValue: "",
    unit: "шт",
    isActive: false,
    category: "trubaVK_NK",
  },
  {
    id: 213,
    img: trubaRtp,
    name: "Крестовина одноплоскостная ВК ПП 110\\50\\50 87° К,серый RTP",
    brand: "RTP",
    quantity: "1 шт",
    price: 160,
    allResidual: 0,
    residualValue: "",
    unit: "шт",
    isActive: false,
    category: "trubaVK_NK",
  },
  {
    id: 214,
    img: trubaRtp,
    name: "Крестовина одноплоскостная ВК ПП 110\\50\\50 45° К,серый RTP",
    brand: "RTP",
    quantity: "1 шт",
    price: 160,
    allResidual: 0,
    residualValue: "",
    unit: "шт",
    isActive: false,
    category: "trubaVK_NK",
  },

  // ==================== ОБРАТНЫЙ КЛАПАН ВК/НК ====================
  {
    id: 215,
    img: trubaRtp,
    name: "Обратный клапан ВК ПП 50ф К,серый RTP",
    brand: "RTP",
    quantity: "1 шт",
    price: 1150,
    allResidual: 0,
    residualValue: "",
    unit: "шт",
    isActive: false,
    category: "trubaVK_NK",
  },
  {
    id: 216,
    img: trubaRtp,
    name: "Обратный клапан ВК ПП 110ф К,серый RTP",
    brand: "RTP",
    quantity: "1 шт",
    price: 1850,
    allResidual: 0,
    residualValue: "",
    unit: "шт",
    isActive: false,
    category: "trubaVK_NK",
  },
  {
    id: 217,
    img: trubaRtp,
    name: "Обратный клапан НК ПП 110ф К,рыжый RTP",
    brand: "RTP",
    quantity: "1 шт",
    price: 2100,
    allResidual: 0,
    residualValue: "",
    unit: "шт",
    isActive: false,
    category: "trubaVK_NK",
  },
  {
    id: 218,
    img: trubaRtp,
    name: "Обратный клапан НК ПП 160ф К,рыжый RTP",
    brand: "RTP",
    quantity: "1 шт",
    price: 3850,
    allResidual: 0,
    residualValue: "",
    unit: "шт",
    isActive: false,
    category: "trubaVK_NK",
  },

  // ==================== ХОМУТЫ (КЛИПСЫ) ====================
  {
    id: 219,
    img: trubaRtp,
    name: "(Клипс) Хомут с защелкой ВК ПП 110х87 К,серый RTP",
    brand: "RTP",
    quantity: "1 шт",
    price: 30,
    allResidual: 0,
    residualValue: "",
    unit: "шт",
    isActive: false,
    category: "other",
  },
  {
    id: 220,
    img: trubaRtp,
    name: "(Клипс) Хомут с защелкой ВК ПП 76х87 К,серый RTP",
    brand: "RTP",
    quantity: "1 шт",
    price: 25,
    allResidual: 0,
    residualValue: "",
    unit: "шт",
    isActive: false,
    category: "other",
  },
  {
    id: 221,
    img: trubaRtp,
    name: "(Клипс) Хомут с защелкой ВК ПП 50х87 К,серый RTP",
    brand: "RTP",
    quantity: "125 шт",
    price: 15,
    allResidual: 1250,
    residualValue: "",
    unit: "шт",
    isActive: true,
    category: "other",
  },
  {
    id: 222,
    img: trubaRtp,
    name: "Хомут в компл (М8) металл 1\\2 (20-25) RTP",
    brand: "RTP",
    quantity: "1 шт",
    price: 25,
    allResidual: 0,
    residualValue: "",
    unit: "шт",
    isActive: false,
    category: "other",
  },
  {
    id: 223,
    img: trubaRtp,
    name: "Хомут в компл (М8) металл 1\\2 (25-29) RTP",
    brand: "RTP",
    quantity: "1 шт",
    price: 28,
    allResidual: 0,
    residualValue: "",
    unit: "шт",
    isActive: false,
    category: "other",
  },
  {
    id: 224,
    img: trubaRtp,
    name: "Хомут в компл (М8) металл 1\\2 (32-34) RTP",
    brand: "RTP",
    quantity: "1 шт",
    price: 32,
    allResidual: 0,
    residualValue: "",
    unit: "шт",
    isActive: false,
    category: "other",
  },
  {
    id: 225,
    img: trubaRtp,
    name: "Хомут в компл (М8) металл1 1\\2 (47-52) RTP",
    brand: "RTP",
    quantity: "1 шт",
    price: 48,
    allResidual: 0,
    residualValue: "",
    unit: "шт",
    isActive: false,
    category: "other",
  },
  {
    id: 226,
    img: trubaRtp,
    name: "Хомут в компл (М8) металл2 1\\2 (73-80) RTP",
    brand: "RTP",
    quantity: "1 шт",
    price: 56,
    allResidual: 0,
    residualValue: "",
    unit: "шт",
    isActive: false,
    category: "other",
  },
  {
    id: 227,
    img: trubaRtp,
    name: "Хомут в компл (М10) металл4 1\\2 (105-115) RTP",
    brand: "RTP",
    quantity: "1 шт",
    price: 60,
    allResidual: 0,
    residualValue: "",
    unit: "шт",
    isActive: false,
    category: "other",
  },
  {
    id: 228,
    img: trubaRtp,
    name: "Хомут в компл (М10) металл6 1\\2 (155-162) RTP",
    brand: "RTP",
    quantity: "1 шт",
    price: 115,
    allResidual: 0,
    residualValue: "",
    unit: "шт",
    isActive: false,
    category: "other",
  },
];


// RTP praduct list export
export const allDataRTPAdir = dataRTPAdir
.filter((itim)=>itim.isActive)
.map((itim)=>({
  ...itim,
  residualValue:itim.price * itim.allResidual
}));

// products count
export const productsCount = allDataRTPAdir.length;

// all products  residual valyue
export const totalResidualValue = allDataRTPAdir.reduce(
  (sum, item) => sum + item.residualValue,
  0
);