import trubaValfex from "@/assets/productImgs/valfex/trubaValfex.jpg";
import ugol90Valfex from "@/assets/productImgs/valfex/ugol90Valfex.jpg";
import ugol45Valfex from "@/assets/productImgs/valfex/ugol45Valfex.jpg";
import muftaValfex from "@/assets/productImgs/valfex/muftaValfex.jpg";
import zagulushkaValfex from "@/assets/productImgs/valfex/zagulishkaValfex.jpg";
import shablonVn from "@/assets/productImgs/valfex/shablonVn.jpg";
import shablonNrValfex from "@/assets/productImgs/valfex/shablonNrValfex.jpg";



// Valfex praduct data
export const dataValfex = [
  {
    id: 1,
    img: trubaValfex,
    name: "Труба полипропиленовая армированная стекловолокном SDR 6 (PN 25) 20ф белый VALFEX",
    brand: "Valfex",
    quantity: "140/4м",
    price: 50,
    allResidual: 14000,
    residualValue: "",
    unit: "м",
    isActive: true,
    category: "trubaPPR",
  },
  {
    id: 2,
    img: trubaValfex,
    name: "Труба полипропиленовая армированная стекловолокном SDR 6 (PN 25) 25ф белый VALFEX",
    brand: "Valfex",
    quantity: "100/4м",
    price: 73,
    allResidual: 15000,
    residualValue: "",
    unit: "м",
    isActive: true,
    category: "trubaPPR",
  },
  {
    id: 3,
    img: trubaValfex,
    name: "Труба полипропиленовая армированная стекловолокном SDR 6 (PN 25) 32ф белый VALFEX",
    brand: "Valfex",
    quantity: "60/4м",
    price: 125,
    allResidual: 9000,
    residualValue: "",
    unit: "м",
    isActive: true,
    category: "trubaPPR",
  },
  {
    id: 4,
    img: trubaValfex,
    name: "Труба полипропиленовая армированная стекловолокном SDR 6 (PN 25) 40ф белый VALFEX",
    brand: "Valfex",
    quantity: "40/4м",
    price: 195,
    allResidual: 8000,
    residualValue: "",
    unit: "м",
    isActive: true,
    category: "trubaPPR",
  },
  {
    id: 5,
    img: ugol90Valfex,
    name: "Угольник 90° 20ф белый VALFEX",
    brand: "Valfex",
    quantity: "400/100 шт",
    price: 6,
    allResidual: 40000,
    residualValue: "",
    unit: "шт",
    isActive: true,
    category: "trubaPPR",
  },
  {
    id: 6,
    img: ugol90Valfex,
    name: "Угольник 90° 25ф белый VALFEX",
    brand: "Valfex",
    quantity: "200/50 шт",
    price: 9,
    allResidual: 24000,
    residualValue: "",
    unit: "шт",
    isActive: true,
    category: "trubaPPR",
  },
  {
    id: 7,
    img: ugol90Valfex,
    name: "Угольник 90° 32ф белый VALFEX",
    brand: "Valfex",
    quantity: "100/25 шт",
    price: 18,
    allResidual: 14000,
    residualValue: "",
    unit: "шт",
    isActive: true,
    category: "trubaPPR",
  },
  {
    id: 8,
    img: ugol90Valfex,
    name: "Угольник 90° 40ф белый VALFEX",
    brand: "Valfex",
    quantity: "60/10 шт",
    price: 35,
    allResidual: 14000,
    residualValue: "",
    unit: "шт",
    isActive: true,
    category: "trubaPPR",
  },
  {
    id: 9,
    img: ugol45Valfex,
    name: "Угольник 45° 20ф белый VALFEX",
    brand: "Valfex",
    quantity: "400/100 шт",
    price: 5,
    allResidual: 40000,
    residualValue: "",
    unit: "шт",
    isActive: true,
    category: "trubaPPR",
  },
  {
    id: 10,
    img: ugol45Valfex,
    name: "Угольник 45° 25ф белый VALFEX",
    brand: "Valfex",
    quantity: "300/50 шт",
    price: 8,
    allResidual: 24000,
    residualValue: "",
    unit: "шт",
    isActive: true,
    category: "trubaPPR",
  },
  {
    id: 11,
    img: ugol45Valfex,
    name: "Угольник 45° 32ф белый VALFEX",
    brand: "Valfex",
    quantity: "150/25 шт",
    price: 17,
    allResidual: 14000,
    residualValue: "",
    unit: "шт",
    isActive: true,
    category: "trubaPPR",
  },
  {
    id: 12,
    img: ugol45Valfex,
    name: "Угольник 45° 40ф белый VALFEX",
    brand: "Valfex",
    quantity: "75/15 шт",
    price: 35,
    allResidual: 14000,
    residualValue: "",
    unit: "шт",
    isActive: true,
    category: "trubaPPR",
  },
  {
    id: 13,
    img: muftaValfex,
    name: "Муфта соединительная 20ф белый VALFEX",
    brand: "Valfex",
    quantity: "500/125 шт",
    price: 5,
    allResidual: 40000,
    residualValue: "",
    unit: "шт",
    isActive: true,
    category: "trubaPPR",
  },
  {
    id: 14,
    img: muftaValfex,
    name: "Муфта соединительная 25ф белый VALFEX",
    brand: "Valfex",
    quantity: "300/75 шт",
    price: 7,
    allResidual: 24000,
    residualValue: "",
    unit: "шт",
    isActive: true,
    category: "trubaPPR",
  },
  {
    id: 15,
    img: muftaValfex,
    name: "Муфта соединительная 32ф белый VALFEX",
    brand: "Valfex",
    quantity: "150/30 шт",
    price: 14,
    allResidual: 14000,
    residualValue: "",
    unit: "шт",
    isActive: true,
    category: "trubaPPR",
  },
  {
    id: 16,
    img: muftaValfex,
    name: "Муфта соединительная 20ф белый VALFEX",
    brand: "Valfex",
    quantity: "100/20 шт",
    price: 25,
    allResidual: 14000,
    residualValue: "",
    unit: "шт",
    isActive: true,
    category: "trubaPPR",
  },
  {
    id: 17,
    img: zagulushkaValfex,
    name: "Заглушка 20ф белый VALFEX",
    brand: "Valfex",
    quantity: "750/125 шт",
    price: 5,
    allResidual: 40000,
    residualValue: "",
    unit: "шт",
    isActive: true,
    category: "trubaPPR",
  },
  {
    id: 18,
    img: zagulushkaValfex,
    name: "Заглушка 25ф белый VALFEX",
    brand: "Valfex",
    quantity: "500/100 шт",
    price: 7,
    allResidual: 24000,
    residualValue: "",
    unit: "шт",
    isActive: true,
    category: "trubaPPR",
  },
  {
    id: 19,
    img: zagulushkaValfex,
    name: "Заглушка 32ф белый VALFEX",
    brand: "Valfex",
    quantity: "250/50 шт",
    price: 10,
    allResidual: 14000,
    residualValue: "",
    unit: "шт",
    isActive: true,
    category: "trubaPPR",
  },
  {
    id: 20,
    img: zagulushkaValfex,
    name: "Заглушка 40ф белый VALFEX",
    brand: "Valfex",
    quantity: "150/25 шт",
    price: 20,
    allResidual: 14000,
    residualValue: "",
    unit: "шт",
    isActive: true,
    category: "trubaPPR",
  },
  {
    id: 21,
    img: shablonVn,
    name: "Комплект настенный для смес. В/Р 20х1/2 VALFEX",
    brand: "Valfex",
    quantity: "20/5 шт",
    price: 110,
    allResidual: 14000,
    residualValue: "",
    unit: "шт",
    isActive: true,
    category: "trubaPPR",
  },
  {
    id: 22,
    img: shablonNrValfex,
    name: "Комплект настенный для смес. Н/Р 20х3/4 VALFEX",
    brand: "Valfex",
    quantity: "20/50 шт",
    price: 200,
    allResidual: 14000,
    residualValue: "",
    unit: "шт",
    isActive: true,
    category: "trubaPPR",
  },
];

// Valfex praduct list export
export const allDataValfex = dataValfex.map((item) => ({
  ...item,
  residualValue: item.price * item.allResidual,
}));


// products count
export const productsCountValfex = allDataValfex.length;

// all products  residual valyue
export const totalResidualValueValfex = allDataValfex.reduce(
  (sum, item) => sum + item.residualValue,
  0
);
