import trubaValfex from "@/assets/productImgs/valfex/trubaValfex.jpg";
import ugol90Valfex from "@/assets/productImgs/valfex/ugol90Valfex.jpg";
import ugol45Valfex from "@/assets/productImgs/valfex/ugol45Valfex.jpg";
import muftaValfex from "@/assets/productImgs/valfex/muftaValfex.jpg";
import zagulushkaValfex from "@/assets/productImgs/valfex/zagulishkaValfex.jpg";
import shablonVn from "@/assets/productImgs/valfex/shablonVn.jpg";
import shablonNrValfex from "@/assets/productImgs/valfex/shablonNrValfex.jpg";



// Valfex praduct data
const dataValfex = [
  {
    id: 1,
    img: trubaValfex,
    name: "Труба PPR/GF/PPR  20х3,4 PN20 белый 4м Valfex",
    brand: "Valfex",
    quantity: "140/4м",
    price: 51,
    allResidual: 14000,
    residualValue: "",
    unit: "м",
    isActive: true,
    category: "trubaPPR",
  },
  {
    id: 2,
    img: trubaValfex,
    name: "Труба PPR/GF/PPR  20х3,4 PN25 белый 4м Valfex",
    brand: "Valfex",
    quantity: "100/4м",
    price: 81,
    allResidual: 15000,
    residualValue: "",
    unit: "м",
    isActive: true,
    category: "trubaPPR",
  },
  {
    id: 3,
    img: trubaValfex,
    name: "Труба PPR/GF/PPR  32х5,4 PN25 белый 4м Valfex",
    brand: "Valfex",
    quantity: "60/4м",
    price: 130,
    allResidual: 9000,
    residualValue: "",
    unit: "м",
    isActive: true,
    category: "trubaPPR",
  },
  {
    id: 4,
    img: trubaValfex,
    name: "Труба PPR/GF/PPR  34х5,4 PN25 белый 4м Valfex",
    brand: "Valfex",
    quantity: "40/4м",
    price: 155,
    allResidual: 8000,
    residualValue: "",
    unit: "м",
    isActive: true,
    category: "trubaPPR",
  },
  {
    id: 5,
    img: ugol90Valfex,
    name: "Угольник PPR  20х90, PN25 белый, Valfex",
    brand: "Valfex",
    quantity: "400/100 шт",
    price: 5,
    allResidual: 40000,
    residualValue: "",
    unit: "шт",
    isActive: true,
    category: "trubaPPR",
  },
  {
    id: 6,
    img: ugol90Valfex,
    name: "Угольник PPR  25х90, PN25 белый, Valfex",
    brand: "Valfex",
    quantity: "240/40 шт",
    price: 8,
    allResidual: 24000,
    residualValue: "",
    unit: "шт",
    isActive: true,
    category: "trubaPPR",
  },
  {
    id: 7,
    img: ugol90Valfex,
    name: "Угольник PPR  32х90, PN25 белый, Valfex",
    brand: "Vlafex",
    quantity: "100/20 шт",
    price: 17,
    allResidual: 14000,
    residualValue: "",
    unit: "шт",
    isActive: true,
    category: "trubaPPR",
  },
  {
    id: 8,
    img: ugol90Valfex,
    name: "Угольник PPR  40х90, PN25 белый, Valfex",
    brand: "Vlafex",
    quantity: "100/20 шт",
    price: 25,
    allResidual: 14000,
    residualValue: "",
    unit: "шт",
    isActive: true,
    category: "trubaPPR",
  },
  {
    id: 9,
    img: ugol45Valfex,
    name: "Угольник PPR  20х45, PN25 белый, Valfex",
    brand: "Valfex",
    quantity: "400/100 шт",
    price: 5,
    allResidual: 40000,
    residualValue: "",
    unit: "шт",
    isActive: true,
    category: "trubaPPR",
  },
  {
    id: 10,
    img: ugol45Valfex,
    name: "Угольник PPR  25х45, PN25 белый, Valfex",
    brand: "Valfex",
    quantity: "240/40 шт",
    price: 8,
    allResidual: 24000,
    residualValue: "",
    unit: "шт",
    isActive: true,
    category: "trubaPPR",
  },
  {
    id: 11,
    img: ugol45Valfex,
    name: "Угольник PPR  32х45, PN25 белый, Valfex",
    brand: "Vlafex",
    quantity: "100/20 шт",
    price: 17,
    allResidual: 14000,
    residualValue: "",
    unit: "шт",
    isActive: true,
    category: "trubaPPR",
  },
  {
    id: 12,
    img: ugol45Valfex,
    name: "Угольник PPR  40х45, PN25 белый, Valfex",
    brand: "Vlafex",
    quantity: "100/20 шт",
    price: 25,
    allResidual: 14000,
    residualValue: "",
    unit: "шт",
    isActive: true,
    category: "trubaPPR",
  },
  {
    id: 13,
    img: muftaValfex,
    name: "Муфта полипропиленовая соединительная PPR  20х45, PN25 белый, Valfex",
    brand: "Valfex",
    quantity: "400/100 шт",
    price: 5,
    allResidual: 40000,
    residualValue: "",
    unit: "шт",
    isActive: true,
    category: "trubaPPR",
  },
  {
    id: 14,
    img: muftaValfex,
    name: "Муфта полипропиленовая соединительная PPR  25х45, PN25 белый, Valfex",
    brand: "Valfex",
    quantity: "240/40 шт",
    price: 8,
    allResidual: 24000,
    residualValue: "",
    unit: "шт",
    isActive: true,
    category: "trubaPPR",
  },
  {
    id: 15,
    img: muftaValfex,
    name: "Муфта полипропиленовая соединительная PPR  32х45, PN25 белый, Valfex",
    brand: "Vlafex",
    quantity: "100/20 шт",
    price: 17,
    allResidual: 14000,
    residualValue: "",
    unit: "шт",
    isActive: true,
    category: "trubaPPR",
  },
  {
    id: 16,
    img: muftaValfex,
    name: "Муфта полипропиленовая соединительная PPR  40х45, PN25 белый, Valfex",
    brand: "Vlafex",
    quantity: "100/20 шт",
    price: 25,
    allResidual: 14000,
    residualValue: "",
    unit: "шт",
    isActive: true,
    category: "trubaPPR",
  },
  {
    id: 17,
    img: zagulushkaValfex,
    name: "Угольник PPR  20х45, PN25 белый, Valfex",
    brand: "Valfex",
    quantity: "400/100 шт",
    price: 5,
    allResidual: 40000,
    residualValue: "",
    unit: "шт",
    isActive: true,
    category: "trubaPPR",
  },
  {
    id: 18,
    img: zagulushkaValfex,
    name: "Угольник PPR  25х45, PN25 белый, Valfex",
    brand: "Valfex",
    quantity: "240/40 шт",
    price: 8,
    allResidual: 24000,
    residualValue: "",
    unit: "шт",
    isActive: true,
    category: "trubaPPR",
  },
  {
    id: 19,
    img: zagulushkaValfex,
    name: "Угольник PPR  32х45, PN25 белый, Valfex",
    brand: "Vlafex",
    quantity: "100/20 шт",
    price: 17,
    allResidual: 14000,
    residualValue: "",
    unit: "шт",
    isActive: true,
    category: "trubaPPR",
  },
  {
    id: 20,
    img: zagulushkaValfex,
    name: "Угольник PPR  40х45, PN25 белый, Valfex",
    brand: "Vlafex",
    quantity: "100/20 шт",
    price: 25,
    allResidual: 14000,
    residualValue: "",
    unit: "шт",
    isActive: true,
    category: "trubaPPR",
  },
  {
    id: 21,
    img: shablonVn,
    name: "Угольник PPR  32х45, PN25 белый, Valfex",
    brand: "Vlafex",
    quantity: "20/5 шт",
    price: 225,
    allResidual: 14000,
    residualValue: "",
    unit: "шт",
    isActive: true,
    category: "trubaPPR",
  },
  {
    id: 23,
    img: shablonNrValfex,
    name: "Угольник PPR  40х45, PN25 белый, Valfex",
    brand: "Vlafex",
    quantity: "20/50 шт",
    price: 250,
    allResidual: 14000,
    residualValue: "",
    unit: "шт",
    isActive: true,
    category: "trubaPPR",
  },
];

// Valfex praduct list export
export const allDataValfex = dataValfex.map((item) => ({
  ...item,
  residualValue: item.price * item.allResidual,
}));


// products count
export const productsCountValfex = allDataValfex.length;

// all products  residual valyue
export const totalResidualValueValfex = allDataValfex.reduce(
  (sum, item) => sum + item.residualValue,
  0
);
